### PR TITLE
fix(): Proper schema usage when running migrations

### LINKED ISSUE #14009: [Bug]: upgrade version from 2.6 to 2.11 facing column o0.version does not exist in orders api
### Package.json file

```JSON
{
  "name": "vinovoss-crm",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "postinstall": "patch-package"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.11.1",
    "@medusajs/cli": "2.11.1",
    "@medusajs/framework": "2.11.1",
    "@medusajs/medusa": "2.11.1",
    "@medusajs/types": "2.11.1",
    "@mikro-orm/core": "6.4.16",
    "@mikro-orm/knex": "6.4.16",
    "@mikro-orm/migrations": "6.4.16",
    "@mikro-orm/postgresql": "6.4.16",
    "@sendgrid/mail": "^8.1.5",
    "@tanstack/react-query": "^5.64.2",
    "@types/nunjucks": "^3.2.6",
    "awilix": "^8.0.1",
    "axios": "^1.8.4",
    "ejs": "^3.1.10",
    "envalid": "^8.1.0",
    "juice": "^11.0.1",
    "nunjucks": "^3.2.4",
    "patch-package": "^8.0.0",
    "pg": "^8.13.0",
    "puppeteer": "^24.10.0",
    "react-hook-form": "^7.54.2",
    "recharts": "^2.15.3",
    "uuid": "^11.1.0"
  },
  "devDependencies": {
    "@faker-js/faker": "^9.4.0",
    "@medusajs/test-utils": "2.11.1",
    "@mikro-orm/cli": "6.4.16",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/nodemailer": "^6.4.17",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11",
    "yalc": "^1.0.0-pre.53"
  },
  "engines": {
    "node": ">=20"
  },
  "packageManager": "yarn@1.22.22+sha512.a6b2f7906b721bba3d67d4aff083df04dad64c399707841b7acf00f6b133b7ac24255f2652fa22ae3534329dc6180534e98d17432037ff6fd140556e2bb3137e"
}
```

### Node.js version

v21

### Database and its version

psql 18

### Operating system name and version

windows

### Browser name

_No response_

### What happended?

inside admin panel I am facing this error 

api: http://localhost:9000/admin/orders?fields=id%2Cstatus%2Ccreated_at%2Cemail%2Cdisplay_id%2Cpayment_status%2Cfulfillment_status%2Ctotal%2Ccurrency_code%2C%2Acustomer%2C%2Asales_channel&limit=20&offset=0&order=-display_id

error: message:"column o0.version does not exist"
type:"invalid_data"

### Expected behavior

api works

### Actual behavior

error: message:"column o0.version does not exist"
type:"invalid_data"

### Link to reproduction repo

v2.6 to v2.11

### PR DESCRIPTION
**Pull request by adrien2p**
**What**
Ensure all migration get executed within the configured schema if configured.
Mikro orm does not manage migration execution within schema properly through the Migration Runner right now.

**Tests**
I ve created a new database and run different tests with public and test schemas, I ve run the migrations and validated that all tables are part of the exepected schema by checking the logged queries as well as checking the `information_schema.tables`

fixes #14009

### CODE REVIEW

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Review by NicolasGorga — APPROVED** [review]
LGTM!!

File: packages/core/utils/src/dal/mikro-orm/custom-db-migrator.ts [hunk 1]
```diff
@@ -32,7 +32,25 @@ export class CustomDBMigrator extends BaseMigrator {
...
+        $this.driver,
+        $this.config
+      ) as Migration
+
+      const customSchema = $this.config.options.schema
+      if (customSchema) {
+        const up = instance.up
+        const down = instance.down
+        instance.up = async function (...args) {
+          this.driver.execute(`SET LOCAL search_path TO ${customSchema}`)
```
Comment (GravlLift) [inline packages/core/utils/src/dal/mikro-orm/custom-db-migrator.ts:45]: @adrien2p I'm using a custom schema and running into some "table not found" sort of errors after upgrading to 2.18.0. I think this here line might be the root cause, but I'm not sure of the wider implications.

Swapping these instructions to use `this.execute` instead of `this.driver.execute` causes the migrations to run successfully. I'm thinking that using `driver` causes the `SET LOCAL` to run in its own transaction context, having no effect on the following migration.

What do you think?

[Related commit, the missing `await` was added in a subsequent commit, but the statement remained effectively unchanged.](https://github.com/medusajs/medusa/commit/9990b69ab76f1a575c6a68875627d16764cc1564)
