### PR TITLE
fix(dashboard): replace native select Element in CountrySelect & ProvinceSelect with Select(Medusa UI).

### LINKED ISSUE #13395: [Bug]: Dark Mode UI Country Select Color Bug
### Package.json file

```JSON
{
  "name": "medusa_test",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.10.1",
    "@medusajs/cli": "2.10.1",
    "@medusajs/draft-order": "^2.10.1",
    "@medusajs/framework": "2.10.1",
    "@medusajs/medusa": "2.10.1",
    "@mikro-orm/core": "6.4.3",
    "@mikro-orm/knex": "6.4.3",
    "@mikro-orm/migrations": "6.4.3",
    "@mikro-orm/postgresql": "6.4.3",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.10.1",
    "@mikro-orm/cli": "6.4.3",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11",
    "yalc": "^1.0.0-pre.53"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.18.0

### Database and its version

PostgreSQL 17.6.1

### Operating system name and version

Debian 12.11

### Browser name

Edge

### What happended?

When using the country select for editing a location, the contrast between the background colors of the select dropdown and the option text isn't there. This only occurs with the country select within the side modal of the location editing it seems. It appears properly in the editing of the tax region. 

It is also correct when using the light theme.

Image

Image

Image

### Expected behavior

Country select CSS and colors should be the same for location editing as well as tax region select. They need to have better contrast.

### Actual behavior

Colors of the options in the select box are too light compared to the background. If the intended behavior is to have a lightly colored dropdown, then the text needs to be darker for the location edit.

### Link to reproduction repo

N/A

### PR DESCRIPTION
**Pull request by patelaryan0914**
Opening Admin Panel /location/:locationId/edit 
The Edit Form was using CountrySelect with native select Html object resulting into missmatch css in dark theme
image
changed to the Medusa Ui's select component for consistent theme changes.
image

FIXES #13395

### CODE REVIEW

**Comment by willbouch** [comment]
Hi! I cannot seem to reproduce on Mac but it looks like the standard MacOS dropdown.
CleanShot 2025-09-16 at 09 32 51@2x

Are you on Windows? Linux? Also, that component is imported in many other pages, do you see the same issue in other places? If yes, maybe it is better fixing the CountrySelect directly so that we fix every place

**Comment by patelaryan0914** [comment]
Yes i was on  Windows using Microsoft Edge i first though to fix the country select but some places it is used as fallback and some places it is used as the component it self so i though to put the select component from medusa. But still let me go through the places and fix all

**Comment by patelaryan0914** [comment]
This request will fix all the Country Select Ui problem Upgraded to Medusa Ui Select Component
Create Stock Location form (Before Fix)
image
Create Stock Location form After Fix
image

Edit Location Form (Before Fix)
image

Edit Location Form (After Fix)
image

**Comment by willbouch** [comment]
Thanks ! Can you just add a changeset in there? Will review

File: packages/admin/dashboard/src/components/inputs/country-select/country-select.tsx [hunk 1]
```diff
@@ -9,70 +9,55 @@ import { TrianglesMini } from "@medusajs/icons"
 import { clx } from "@medusajs/ui"
 import { useTranslation } from "react-i18next"
 import { countries } from "../../../lib/data/countries"
+import { Select } from "@medusajs/ui"
 
 export const CountrySelect = forwardRef<
-  HTMLSelectElement,
-  ComponentPropsWithoutRef<"select"> & {
+  HTMLButtonElement,
```
Comment (willbouch) [inline packages/admin/dashboard/src/components/inputs/country-select/country-select.tsx:12]: Why? It looks more like a select than a button to me!?

Comment (patelaryan0914) [reply packages/admin/dashboard/src/components/inputs/country-select/country-select.tsx:12]: Yes, this is a Select component. Native select doesn’t give us the same freedom of styling (especially for things like dark mode), so Medusa UI implements it using a button + listbox pattern to achieve the same effect with full CSS control.

Comment (patelaryan0914) [reply packages/admin/dashboard/src/components/inputs/country-select/country-select.tsx:12]: added the change set.
Also this was my first opensource contribution so please guide through the journey many more to come.
Thank You.
Hoping this will merge.

File: packages/admin/dashboard/src/components/inputs/country-select/country-select.tsx [hunk 2]
```diff
@@ -9,70 +9,55 @@ import { TrianglesMini } from "@medusajs/icons"
...
+              value={country.iso_2.toLowerCase()}
+            >
+              {country.display_name}
+            </Select.Item>
+          ))}
+        </Select.Content>
+      </Select>
+    </div>
+  )
+})
```
[the remark this answers is not in the document]
Comment (willbouch) [reply packages/admin/dashboard/src/components/inputs/country-select/country-select.tsx:51]: @patelaryan0914 This is what I am concerned about too. It seems like you refactored the component quite a bit and I am not sure if all is supported

File: packages/admin/dashboard/src/components/inputs/country-select/country-select.tsx (hunk 1 above)
Comment (willbouch) [reply packages/admin/dashboard/src/components/inputs/country-select/country-select.tsx:12]: No worries, we will get this merged

File: packages/admin/dashboard/src/components/inputs/country-select/country-select.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (patelaryan0914) [reply packages/admin/dashboard/src/components/inputs/country-select/country-select.tsx:51]: So every where the native select is used the problem of theming is there even with the ProvinceSelector
image
the issue you are concerned is it wont take the default props?

[the remark this answers is not in the document]
Comment (willbouch) [reply packages/admin/dashboard/src/components/inputs/country-select/country-select.tsx:51]: Yes, we used to spread the props and pass them done in the native select, but this was removed. I am not saying it is necessary, but it looks like this could be causing issues. And the cursor bot flagged it too

File: .changeset/pink-zebras-fetch.md [hunk 3]
```diff
@@ -0,0 +1,6 @@
+---
+"@medusajs/stock-location": major
```
[the remark this answers is not in the document]
Comment (patelaryan0914) [reply .changeset/pink-zebras-fetch.md]: @willbouch  I have changed in the admin dashboard is this @medusajs/dashboard the package. To include in the change set?

**Comment by patelaryan0914** [comment]
Can you please check the last commit for CountrySelect component so there is different native props in the Select Component (Medusa UI kit) and the native select element its only of className. Select(Medusa Ui) doesnt allow to pass className as props other all it works fine the onBlur, name are passed in the spread operator with field.

And this majorly fixes all the places but there are some inconsistencies while using it as in some place the Select is used directly and in fallback if countries are not available than the CountrySelect component is Used. lastly the ProvinceSelect should be also fix if this works should it be in another commit or the same commit?

Now everything's fine... will add the change set. 

Thanks for coordination really feeling confident now this experience is so valuable for me.

File: .changeset/pink-zebras-fetch.md [hunk 4]
```diff
@@ -0,0 +1,6 @@
...
+---
+
+This Fixes inconsistency of theme in Country Select Element in dark theme
```
Comment (willbouch) [inline .changeset/pink-zebras-fetch.md]: This here should just be the PR name :)

File: .changeset/pink-zebras-fetch.md (hunk 3 above)
[the remark this answers is not in the document]
Comment (willbouch) [reply .changeset/pink-zebras-fetch.md]: In your case, it does not introduce any breaking change. This is simply a patch, so the changeset should say "patch" instead of "major". Major would mean that Medusa bumps from version 2.10.x to 3.0.0 😅

**Comment by willbouch** [comment]
> Can you please check the last commit for CountrySelect component so there is different native props in the Select Component (Medusa UI kit) and the native select element its only of className. Select(Medusa Ui) doesnt allow to pass className as props other all it works fine the onBlur, name are passed in the spread operator with field.
> 
> And this majorly fixes all the places but there are some inconsistencies while using it as in some place the Select is used directly and in fallback if countries are not available than the CountrySelect component is Used. lastly the ProvinceSelect should be also fix if this works should it be in another commit or the same commit?
> 
> Now everything's fine... will add the change set.
> 
> Thanks for coordination really feeling confident now this experience is so valuable for me.

Province select component also has the same bug? I would fix in same PR if that is the case

File: .changeset/pink-zebras-fetch.md (hunk 4 above)
Comment (patelaryan0914) [reply .changeset/pink-zebras-fetch.md]: ohk and what about the package @medusajs/dashboard because there is nothing like @medusajs/admin

File: .changeset/pink-zebras-fetch.md (hunk 3 above)
[the remark this answers is not in the document]
Comment (patelaryan0914) [reply .changeset/pink-zebras-fetch.md]: ohhk 😅

**Comment by patelaryan0914** [comment]
And have you got why we are using HTMLButtonElement instead of HTMLSelectElement because Select.Trigger under the hood uses button so if we are using the HTMLSelectElement than the ref is mismatched. 


Yes Province selector also has the same bug would solve it in the next commit within this PR.

Thanks for your help.

File: .changeset/pink-zebras-fetch.md (hunk 4 above)
Comment (willbouch) [reply .changeset/pink-zebras-fetch.md]: I replaced the PR name. The package you are impacting is "dashboard". The changeset should reflect that. Currently, it says "stock-location" but this is wrong

Comment (willbouch) [reply .changeset/pink-zebras-fetch.md]: https://github.com/changesets/changesets/blob/main/docs/adding-a-changeset.md

Comment (patelaryan0914) [reply .changeset/pink-zebras-fetch.md]: yeah i was about to change in the last commit so i asked you.

File: packages/admin/dashboard/src/components/inputs/province-select/province-select.tsx [hunk 5]
```diff
@@ -55,9 +44,12 @@ export const ProvinceSelect = forwardRef<
...
       ([iso2, name]) => {
         return (
-          <option key={iso2} value={valueAs === "iso_2" ? iso2 : name}>
+          <Select.Item
+            key={iso2}
+            value={valueAs === "iso_2" ? iso2.toLowerCase() : name}
+          >
             {name}
-          </option>
+          </Select.Item>
```
[the remark this answers is not in the document]
Comment (patelaryan0914) [reply packages/admin/dashboard/src/components/inputs/province-select/province-select.tsx:52]: So the api itself stores the province code in lowercase. It wont break the backward compatibility

**Comment by patelaryan0914** [comment]
Province Select before fix
Screenshot 2025-09-26 132521

Province Select After Fix
Screenshot 2025-09-26 134849


This works fine checked both of them.

**Comment by willbouch** [comment]
Hi @patelaryan0914 can you take a look at the conflicts?

**Comment by patelaryan0914** [comment]
Yup Solved the merge conflict. @willbouch

**Comment by willbouch** [comment]
I tested on Mac and the hover seems to be broken.. Initially, I see the hover, but if I click elsewhere (so the select looses focus) and then open the select again, the hover does not work anymore

https://github.com/user-attachments/assets/8fcf7a80-f995-4ec3-9f87-090e71d5b4e8

**Comment by patelaryan0914** [comment]
So, the component I have used which is Medusa Select is itself has hover broken. 

https://github.com/user-attachments/assets/584c70ea-e4b9-482e-a022-494bddcf1f01

**Comment by willbouch** [comment]
> So, the component I have used which is Medusa Select is itself has hover broken.
> 
>  Select.-.Medusa.UI.and.4.more.pages.-.Personal.-.Microsoft.Edge.2025-10-04.11-35-10.mp4

You are right. We can let that one slip and create an issue. Will add something in our backlog. If you want to fix that as well, it can be done in another PR :)

**Comment by willbouch** [comment]
@fPolic Gave it a spin locally and it looked fine. Wdyt?

File: packages/admin/dashboard/src/routes/locations/location-edit/components/edit-location-form/edit-location-form.tsx [hunk 6]
```diff
@@ -4,12 +4,11 @@ import { Button, Input, toast } from "@medusajs/ui"
 import { useForm } from "react-hook-form"
 import { useTranslation } from "react-i18next"
 import * as zod from "zod"
-
 import { Form } from "../../../../../components/common/form"
-import { CountrySelect } from "../../../../../components/inputs/country-select"
 import { RouteDrawer, useRouteModal } from "../../../../../components/modals"
 import { KeyboundForm } from "../../../../../components/utilities/keybound-form"
 import { useUpdateStockLocation } from "../../../../../hooks/api/stock-locations"
+import { CountrySelect } from "../../../../../components/inputs/country-select/country-select"
```
Comment (fPolic) [inline packages/admin/dashboard/src/routes/locations/location-edit/components/edit-location-form/edit-location-form.tsx:11]:
```suggestion
import { CountrySelect } from "../../../../../components/inputs/country-select"
```

**Review by fPolic — APPROVED** [review]
LGTM - thanks for the contribution!

**Comment by patelaryan0914** [comment]
@willbouch Hello, what is my role now once? 
can you let me know the further process?

**Comment by willbouch** [comment]
@patelaryan0914. I'll take it from here. Thanks!
