### PR TITLE
fix: Use the correct currency for edit promotions form

### LINKED ISSUE #11297: [Bug]: Wrong display of currency when editing promotion
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "^2.4.0",
    "@medusajs/cli": "^2.4.0",
    "@medusajs/framework": "^2.4.0",
    "@medusajs/medusa": "^2.4.0",
    "@mikro-orm/core": "^6.4.5",
    "@mikro-orm/knex": "^6.4.5",
    "@mikro-orm/migrations": "^6.4.5",
    "@mikro-orm/postgresql": "^6.4.5",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "^2.4.0",
    "@mikro-orm/cli": "^6.4.5",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  },
  "packageManager": "yarn@1.22.22"
}
```

### Node.js version

20.16.0

### Database and its version

PostgreSQL 16.6

### Operating system name and version

MacOS Sonoma 14.3.1

### Browser name

Chrome

### What happended?

When editing a promotion, the currency is not the same as the chose one.

Image
Image

### Expected behavior

Same currency

### Actual behavior

Defaults to dollars

### Link to reproduction repo

-

### PR DESCRIPTION
**Pull request by sradevski**
FIXES #11297

### CODE REVIEW

File: packages/admin/dashboard/src/routes/promotions/promotion-edit-details/components/edit-promotion-form/edit-promotion-details-form.tsx [hunk 1]
```diff
@@ -247,8 +250,8 @@ export const EditPromotionDetailsForm = ({
                           onValueChange={(val) =>
                             onChange(val ? parseInt(val) : null)
                           }
-                          code={"USD"}
-                          symbol={getCurrencySymbol("USD")}
+                          code={currencyCode}
```
Comment (olivermrbl) [inline packages/admin/dashboard/src/routes/promotions/promotion-edit-details/components/edit-promotion-form/edit-promotion-details-form.tsx:253]: this was hardcoded all this time? 😄

**Review by kasperkristensen — APPROVED** [review]

**Review by olivermrbl — APPROVED** [review]

File: packages/admin/dashboard/src/routes/promotions/promotion-edit-details/components/edit-promotion-form/edit-promotion-details-form.tsx (hunk 1 above)
Comment (sradevski) [reply packages/admin/dashboard/src/routes/promotions/promotion-edit-details/components/edit-promotion-form/edit-promotion-details-form.tsx:253]: Yup :D it seems only here though, I did some quick search
