### PR TITLE
fix(index): logical operators

### LINKED ISSUE #13132: Missing example on how to use $and/$or operators when using `query.index`
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

There is no clear instructions on how to correctly use special $ operators such as $and / $or when using index module

It would be great to showcase how to compose query similar to this:

```ts
const { data: products } = await query.index({
  entity: "product",
  filters: {
    $and: [
      { status: "published" },
      {
        $or: [
          { title: { $ilike: "%adidas%" } },
          { brand: { name: { $ilike: "%adidas%" } } }
        ]
      }
    ]
  }
})
```

This query was suggested by the AI bot, however it does not run and instead throws an error
`Error: Field $and is not indexed.`

### How can this issue be resolved?

1. providing clear instructions on how to use `$ operators` when utilizing `query.index` module
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

### PR DESCRIPTION
**Pull request by carlos-r-l-rodrigues**
What:
 - Fixes `$and` and `$or` operators
 - Emits event on Link dismissal
 - Fixes custom module index

FIXES: https://github.com/medusajs/medusa/issues/13132 https://github.com/medusajs/medusa/issues/13142 https://github.com/medusajs/medusa/issues/13097

### CODE REVIEW

File: packages/modules/index/src/utils/query-builder.ts [hunk 1]
```diff
@@ -209,12 +216,16 @@ export class QueryBuilder {
   private parseWhere(
     aliasMapping: { [path: string]: string },
     obj: object,
-    builder: Knex.QueryBuilder
+    builder: Knex.QueryBuilder,
+    parentPath: string = ""
   ) {
+    console.log(JSON.stringify(obj, null, 2), "PARENT", parentPath)
```
Comment (willbouch) [inline packages/modules/index/src/utils/query-builder.ts]: debug log that should be removed?

Comment (carlos-r-l-rodrigues) [reply packages/modules/index/src/utils/query-builder.ts]: nice catch. thanks

**Comment by martinerko** [comment]
@willbouch  I have tested it but unable to confirm whether it works. 
I am afraid the index module is completely broken since version 2.8.6 and it does not index custom modules.
see https://github.com/medusajs/medusa/issues/13142
also https://github.com/medusajs/medusa/issues/13097

**Comment by martinerko** [comment]
@carlos-r-l-rodrigues I can confirm that:
- filtering by custom entities works again fine
- link dismiss is correctly updating data

however `$and` and `$or` are still **not** working, even typescript complains that these two operators do not exists in index module.

**Comment by carlos-r-l-rodrigues** [comment]
> however `$and` and `$or` are still **not** working, even typescript complains that these two operators do not exists in index module.

Do you have the same runtime error as before? or is it just TS? @martinerko 
Can you share the `filters` from your query, please.

**Comment by martinerko** [comment]
it seems like using $and/$or does not work on custom fields.
here are some test cases

```ts

// works

const { data: products } = await query.index({
  entity: "product",
  fields: [
    "id",
    "title",
    "status",
    "brand.*"
  ],
  filters: {
    $or: [
      {
        status: "published"
      },
      {
        status: "draft"
      }
    ]
  }
})

// works

const { data: products } = await query.index({
  entity: "product",
  fields: [
    "id",
    "title",
    "status",
    "brand.*"
  ],
  filters: {
    brand: {
      name: {
        $ilike: "%ike%"
      }
    }
  }
})

// does not work

const { data: products } = await query.index({
  entity: "product",
  fields: [
    "id",
    "title",
    "status",
    "brand.*"
  ],
  filters: {
    $or: [
      {
        brand: {
          name: {
            $ilike: "%ike%"
          }
        }
      },
      {
        brand: {
          name: {
            $ilike: "%ike%"
          }
        }
      }
    ]
  }
})

// does not work

const { data: products } = await query.index({
  entity: "product",
  fields: [
    "id",
    "title",
    "status",
    "brand.*"
  ],
  filters: {
    $and: [
      {
        status: "published"
      },
      {
        brand: {
          name: {
            $ilike: "%ike%"
          }
        }
      }
    ]
  }
})

```

**Comment by martinerko** [comment]
@carlos-r-l-rodrigues here is the error thrown when I execute the failing examples:

```sh
error:   Expected 1 bindings, saw 2
Error: Expected 1 bindings, saw 2
    at replaceRawArrBindings (D:\dev\admin\node_modules\knex\lib\formatter\rawFormatter.js:27:11)
    at Raw.toSQL (D:\dev\admin\node_modules\knex\lib\raw.js:77:13)
    at unwrapRaw (D:\dev\admin\node_modules\knex\lib\formatter\wrappingFormatter.js:116:19) 
```

**Comment by carlos-r-l-rodrigues** [comment]
@martinerko this should be fixed on `2.9.0-snapshot-20250806132654`
Thanks for the feedback.

File: packages/modules/index/src/utils/query-builder.ts [hunk 2]
```diff
@@ -9,6 +9,9 @@ import { Knex } from "@mikro-orm/knex"
 import { OrderBy, QueryFormat, QueryOptions, Select } from "@types"
 import { getPivotTableName, normalizeTableName } from "./normalze-table-name"
 
+const AND_OPERATOR = "$and"
```
Comment (olivermrbl) [inline packages/modules/index/src/utils/query-builder.ts:12]: Hehe some pretty wild gymnastics going on in this file, so a little bit hard to review 😄

**Review by olivermrbl — APPROVED** [review]
