### PR TITLE
fix(types): missing rules in prices types

### LINKED ISSUE #12910: Add `rules` property to`CreateFlatRateShippingOptionPriceRecord`
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Description

The [pricing documentation](https://docs.medusajs.com/resources/commerce-modules/pricing/price-rules#how-to-set-rules-on-a-price) shows how to set price rules on shipping options, but the TypeScript types don't support the `rules` property, causing a compilation error.

### Reference

The documentation shows this example:

```typescript
const { result } = await createShippingOptionsWorkflow(container)
  .run({
    input: [{
      name: "Standard Shipping",
      service_zone_id: "serzo_123",
      shipping_profile_id: "sp_123",
      provider_id: "prov_123",
      type: {
        label: "Standard",
        description: "Standard shipping",
        code: "standard",
      },
      price_type: "flat",
      prices: [
        // default price
        {
          currency_code: "usd",
          amount: 10,
          rules: {}, // ← This should work according to docs
        },
        // price if cart total >= $100
        {
          currency_code: "usd",
          amount: 0,
          rules: {
            item_total: {
              operator: "gte",
              value: 100,
            },  // ← This should work according to docs
          },
        },
      ],
    }],
  })
```

### Actual error

`Object literal may only specify known properties, and 'rules' does not exist in type 'CreateFlatRateShippingOptionPriceRecord'.ts(2353)`

The TypeScript compiler indicates that the `rules` property doesn't exist in the `CreateFlatRateShippingOptionPriceRecord` type.

### Excepted Behavior

One of these should be true:

1. The rules property should be supported in CreateFlatRateShippingOptionPriceRecord type
2. The documentation should be updated to reflect the correct way to implement price rules for shipping options

### How can this issue be resolved?

1. Update the TypeScript definitions to include the `rules` property
2. Update the documentation to show the correct implementation
3. Provide a working example of how to implement conditional shipping pricing

### Are you interested in working on this issue?

- [x] I would like to fix this issue

### LINKED ISSUE #13610: [Bug]: Unable to adjust Shipping Prices based on Customer Group
### Package.json file

```JSON
{
  "name": "portal-backend",
  "version": "2025.9.24",
  "scripts": {
    "build": "medusa build",
    "dev": "medusa develop",
    "dev:email": "email dev --dir ./src/modules/resend/emails",
    "predeploy": "medusa db:migrate",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "start:server": "cd .medusa/server && npm i --omit=dev && npm run predeploy && npm run start",
    "start:worker": "cd .medusa/server && npm i --omit=dev && npm run start",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.10.3",
    "@medusajs/cli": "2.10.3",
    "@medusajs/draft-order": "2.10.3",
    "@medusajs/framework": "2.10.3",
    "@medusajs/js-sdk": "2.10.3",
    "@medusajs/medusa": "2.10.3",
    "@medusajs/ui": "4.0.23",
    "@medusajs/workflows-sdk": "2.10.3",
    "@mikro-orm/core": "6.4.3",
    "@mikro-orm/knex": "6.4.3",
    "@mikro-orm/migrations": "6.4.3",
    "@mikro-orm/postgresql": "6.4.3",
    "@react-email/components": "0.5.1",
    "@react-email/render": "^1.2.1",
    "awilix": "^8.0.1",
    "jspdf": "^3.0.2",
    "pg": "^8.16.3",
    "resend": "^6.0.1",
    "stripe": "^18.4.0",
    "zod": "^3.25.76"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.10.3",
    "@medusajs/types": "2.10.3",
    "@medusajs/ui-preset": "2.10.3",
    "@mikro-orm/cli": "6.4.3",
    "@react-email/preview-server": "^4.2.8",
    "@swc/core": "^1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.14",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-email": "^4.2.8",
    "ts-node": "^10.9.2",
    "typescript": "^5.8.3",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=22"
  }
}
```

### Node.js version

v22.19.0

### Database and its version

PostgreSQL 16.10

### Operating system name and version

Debian 16.10-1.pgdg13+1

### Browser name

_No response_

### What happended?

Unable to add a price set for free shipping based on customer group - documentation shows it configurable through workflows and through the pricing module, but both do not work.
When trying to add `rules` in the `createShippingOptionsWorkflow` under the `prices` list, the follow error displays: `Object literal may only specify known properties, and 'rules' does not exist in type 'CreateFlatRateShippingOptionPriceRecord'.ts(2353)`
When trying to add through `pricingModule.addPrices` function (and ignoring errors), get the following error: `MedusaError: operator should be one of gte, lte, gt, lt, eq`

### Expected behavior

Should be able to create a pricing set that allows free shipping based on customer group affiliation

### Actual behavior

Cannot implement a pricing value to enable free shipping based on customer group

### Link to reproduction repo

https://github.com/AIApothecary/Portal

### PR DESCRIPTION
**Pull request by willbouch**
This was missing from the types although they are in validators. https://github.com/medusajs/medusa/blob/bb6cc586f7e883ea2eaa29ef459f8b3dbd3a345b/packages/medusa/src/api/admin/shipping-options/validators.ts#L88-L103

CLOSES #13610
CLOSES #12910

### CODE REVIEW

**Review by adrien2p — APPROVED** [review]

File: packages/core/types/src/http/shipping-option/admin/payloads.ts [hunk 1]
```diff
@@ -184,6 +157,30 @@ export interface AdminCreateShippingOption {
   metadata?: Record<string, unknown>
 }
 
+/**
```
Comment (willbouch) [inline packages/core/types/src/http/shipping-option/admin/payloads.ts:160]: This reflects what we have [here](https://github.com/medusajs/medusa/blob/3f1e92dfb2507131f5fab6501a38c02d0d4d5335/packages/core/types/src/workflow/fulfillment/create-shipping-options.ts#L90-L112) more accurately
