### PR TITLE
fix(dashboard): export with filters not working

### LINKED ISSUE #13470: [Bug]: Product CSV Export is not escaping properly and filters are ignored
### Package.json file

```JSON
{
  "name": "@oprema24/medusa",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "migrate": "medusa db:migrate",
    "test": "jest --config jest.config.js",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.10.1",
    "@medusajs/cli": "2.10.1",
    "@medusajs/framework": "2.10.1",
    "@medusajs/js-sdk": "2.10.1",
    "@medusajs/medusa": "2.10.1",
    "@medusajs/types": "2.10.1",
    "@medusajs/workflows-sdk": "2.10.1",
    "@mikro-orm/core": "6.4.3",
    "@mikro-orm/knex": "6.4.3",
    "@mikro-orm/migrations": "6.4.3",
    "@mikro-orm/postgresql": "6.4.3",
    "@oprema24/medusa": "file:",
    "@react-email/components": "^0.4.0",
    "awilix": "^8.0.1",
    "commander": "^12.0.0",
    "csv-parser": "3.2.0",
    "fast-csv": "^5.0.2",
    "meilisearch": "^0.51.0",
    "nodemailer": "^6.9.0",
    "openai": "^5.7.0",
    "pg": "^8.13.0",
    "zod": "3.24.3"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.10.1",
    "@mikro-orm/cli": "6.4.3",
    "@react-email/preview-server": "4.2.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/nodemailer": "^6.4.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-email": "^4.2.7",
    "ts-jest": "^29.2.6",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11",
    "yalc": "^1.0.0-pre.53"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.16.0

### Database and its version

PostgreSQL 16.9

### Operating system name and version

WSL ubuntu0.24.04.1

### Browser name

_No response_

### What happended?

I've tried to export and then import products on my Medusa instance, however, I've run into multiple issues. 
Some characters seem to not get correctly serialized. Instances of what is not getting correctly serialized is:
1. double single quotes ''

error:   Invalid Closing Quote: got " " at line 545 instead of delimiter, record delimiter, trimable character (if activated) or comment

Interestingly it doesn't happen in isolation 

2. bulletpoint sign •  which gets serialized as a single quotation mark in already open quotes, which inadvertendly closes them (same error as above)

3. When trying to create a file to reproduce this, I've noticed that the filters set get ignored when exporting, i.e. the whole database is always exported. The product list correctly filters the products and the preview of the export page also correctly shows the filter applied.

### Expected behavior

Exporting a csv and importing it works without issues.

### Actual behavior

Unexpected error is thrown:
```
error:   Invalid Opening Quote: a quote is found on field "Product Description" at line 2, value is "Test product with a "
{
  message: 'Invalid Opening Quote: a quote is found on field "Product Description" at line 2, value is "Test product with a "',
  name: 'Error',
  stack: 'Error: Invalid Opening Quote: a quote is found on field "Product Description" at line 2, value is "Test product with a "\n' +
    '    at Object.parse (/home/kraghot/workspace/oprema24/node_modules/csv-parse/dist/cjs/index.cjs:1112:21)\n' +
    '    at Parser._transform (/home/kraghot/workspace/oprema24/node_modules/csv-parse/dist/cjs/index.cjs:1783:26)\n' +
    '    at Parser.Transform._write (node:internal/streams/transform:171:8)\n' +
    '    at writeOrBuffer (node:internal/streams/writable:572:12)\n' +
    '    at _write (node:internal/streams/writable:501:10)\n' +
    '    at Parser.Writable.write (node:internal/streams/writable:510:10)\n' +
    '    at ReadStream.ondata (node:internal/streams/readable:1009:22)\n' +
    '    at ReadStream.emit (node:events:518:28)\n' +
    '    at ReadStream.emit (node:domain:489:12)\n' +
    '    at addChunk (node:internal/streams/readable:561:12)\n' +
    '    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)\n' +
    '    at ReadStream.Readable.push (node:internal/streams/readable:392:5)\n' +
    '    at node:internal/fs/streams:289:14\n' +
    '    at FSReqCallback.wrapper [as oncomplete] (node:fs:672:5)\n' +
    '    at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17)\n' +
    '⮑ sat /home/kraghot/workspace/oprema24/node_modules/@medusajs/core-flows/dist/product/workflows/import-products-as-chunks.js: chunks -> normalize-product-csv-to-chunks (invoke)]',
  code: 'INVALID_OPENING_QUOTE',
  bytes: 1108,
  comment_lines: 0,
  empty_lines: 0,
  invalid_field_length: 0,
  lines: 2,
  records: 0,
  columns: [
    { name: 'Product Id' },
    { name: 'Product Handle' },
    { name: 'Product Title' },
    { name: 'Product Subtitle' },
    { name: 'Product Description' },
    { name: 'Product Status' },
    { name: 'Product Thumbnail' },
    { name: 'Product Weight' },
    { name: 'Product Length' },
    { name: 'Product Width' },
    { name: 'Product Height' },
    { name: 'Product Origin Country' },
    { name: 'Product Material' },
    { name: 'Product Collection Id' },
    { name: 'Product Type Id' },
    { name: 'Product Discountable' },
    { name: 'Product External Id' },
    { name: 'Product Created At' },
    { name: 'Product Deleted At' },
    { name: 'Product Hs Code' },
    { name: 'Product Image 1' },
    { name: 'Product Image 10' },
    { name: 'Product Image 11' },
    { name: 'Product Image 2' },
    { name: 'Product Image 3' },
    { name: 'Product Image 4' },
    { name: 'Product Image 5' },
    { name: 'Product Image 6' },
    { name: 'Product Image 7' },
    { name: 'Product Image 8' },
    { name: 'Product Image 9' },
    { name: 'Product Is Giftcard' },
    { name: 'Product Mid Code' },
    { name: 'Product Sales Channel 1' },
    { name: 'Product Updated At' },
    { name: 'Variant Id' },
    { name: 'Variant Title' },
    { name: 'Variant Sku' },
    { name: 'Variant Upc' },
    { name: 'Variant Ean' },
    { name: 'Variant Hs Code' },
    { name: 'Variant Mid Code' },
    { name: 'Variant Manage Inventory' },
    { name: 'Variant Allow Backorder' },
    { name: 'Variant Barcode' },
    { name: 'Variant Created At' },
    { name: 'Variant Deleted At' },
    { name: 'Variant Height' },
    { name: 'Variant Length' },
    { name: 'Variant Material' },
    { name: 'Variant Metadata' },
    { name: 'Variant Option 1 Name' },
    { name: 'Variant Option 1 Value' },
    { name: 'Variant Origin Country' },
    { name: 'Variant Price [EUR]' },
    { name: 'Variant Price EUR' },
    { name: 'Variant Product Id' },
    { name: 'Variant Updated At' },
    { name: 'Variant Variant Rank' },
    { name: 'Variant Weight' },
    { name: 'Variant Width' }
  ],
  error: undefined,
  header: false,
  index: 4,
  raw: undefined,
  column: 'Product Description',
  quoting: false,
  field: 'Test product with a '
}
```

Description of the product exported: `Test product with a • character`

Resulting CSV file:
```
Product Id,Product Handle,Product Title,Product Subtitle,Product Description,Product Status,Product Thumbnail,Product Weight,Product Length,Product Width,Product Height,Product Origin Country,Product Material,Product Collection Id,Product Type Id,Product Discountable,Product External Id,Product Created At,Product Deleted At,Product Hs Code,Product Image 1,Product Image 10,Product Image 11,Product Image 2,Product Image 3,Product Image 4,Product Image 5,Product Image 6,Product Image 7,Product Image 8,Product Image 9,Product Is Giftcard,Product Mid Code,Product Sales Channel 1,Product Updated At,Variant Id,Variant Title,Variant Sku,Variant Upc,Variant Ean,Variant Hs Code,Variant Mid Code,Variant Manage Inventory,Variant Allow Backorder,Variant Barcode,Variant Created At,Variant Deleted At,Variant Height,Variant Length,Variant Material,Variant Metadata,Variant Option 1 Name,Variant Option 1 Value,Variant Origin Country,Variant Price [EUR],Variant Price EUR,Variant Product Id,Variant Updated At,Variant Variant Rank,Variant Weight,Variant Width
prod_01K4TN499JEWGTZG85V60Z47WB,bla,Test Product,test,Test product with a " character,draft,,,,,,,,,,true,,2025-09-10T20:29:59.987Z,,,,,,,,,,,,,,false,,sc_01K43N216DQA7C47CR1HGV7GHN,2025-09-10T21:31:08.928Z,variant_01K4TN49APVW4ESH319MQDF320,Default variant,111111111,,,,,false,false,,2025-09-10T20:30:00.022Z,,,,,,Default option,Default option value,,1,1,prod_01K4TN499JEWGTZG85V60Z47WB,2025-09-10T20:30:00.022Z,0,,
```

### Link to reproduction repo

N/A

### PR DESCRIPTION
**Pull request by willbouch**
CLOSES #13470 
CLOSES CORE-1245

The export never seem to pick up on the filters. Looks like the feature was just never completed

### CODE REVIEW

File: packages/admin/dashboard/src/components/modals/hooks/use-state-aware-to.tsx [hunk 1]
```diff
@@ -15,12 +16,17 @@ export const useStateAwareTo = (prev: string | Partial<Path>) => {
   const to = useMemo(() => {
     const params = location.state?.restore_params
 
-    if (!params) {
-      return prev
+    if (params) {
```
Comment (willbouch) [inline packages/admin/dashboard/src/components/modals/hooks/use-state-aware-to.tsx:19]: While working on this, I also noticed that when I do the following:
1. Apply filters in the products table
2. Click Export (or Import)
3. Cancel

I was sent back to the products table but the filters were "reseted". It is a bit annoying, so I implemented a fix here for this. I did not modify the behaviour when we hit "Create", since I guess it makes sense to reset the filters to make sure the created products appears on the screen when we are done

File: packages/admin/dashboard/src/routes/products/product-export/product-export.tsx [hunk 2]
```diff
@@ -24,24 +25,23 @@ export const ProductExport = () => {
...
   const { t } = useTranslation()
-  const { mutateAsync } = useExportProducts()
+  const { searchParams } = useProductTableQuery({})
+
+  const { mutateAsync } = useExportProducts({ ...searchParams })
   const { handleSuccess } = useRouteModal()
 
   const handleExportRequest = async () => {
-    await mutateAsync(
-      {},
```
Comment (willbouch) [inline packages/admin/dashboard/src/routes/products/product-export/product-export.tsx:32]: This is what I mean when I say that the feature looked incomplete

Comment (olivermrbl) [reply packages/admin/dashboard/src/routes/products/product-export/product-export.tsx:32]: Nice catch, I think you are right!

**Review by olivermrbl — APPROVED** [review]
LGTM
