### PR TITLE
fix(types): pluralize words ending in s like status

### LINKED ISSUE #13234: [Bug]: Type hints for CRUD methods fails to pluralised model name ending with 's'
### Package.json file

```JSON
{
  "name": "porezlamina-admin",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "build:app": "rm -rf app-build && mkdir app-build && medusa build && cp -r .medusa/server app-build && cp -r .medusa/types app-build  && cd app-build/server && cp ../../.app.env .env",
    "build:worker": "rm -rf worker-build && mkdir worker-build && medusa build && cp -r .medusa/server worker-build  && cp -r .medusa/types worker-build && cd worker-build/server && cp ../../.worker.env .env",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "dev:email": "email dev --dir ./src/modules/resend/emails",
    "predeploy": "medusa db:migrate",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.8.7",
    "@medusajs/cli": "2.8.7",
    "@medusajs/framework": "2.8.7",
    "@medusajs/medusa": "2.8.7",
    "@mikro-orm/core": "6.4.3",
    "@mikro-orm/knex": "6.4.3",
    "@mikro-orm/migrations": "6.4.3",
    "@mikro-orm/postgresql": "6.4.3",
    "@react-email/components": "0.3.2",
    "awilix": "^8.0.1",
    "csv-stringify": "^6.6.0",
    "pg": "^8.13.0",
    "resend": "^4.7.0",
    "slugify": "^1.6.6",
    "ulid": "^3.0.1",
    "xlsx": "^0.18.5"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.8.7",
    "@mikro-orm/cli": "6.4.3",
    "@react-email/preview-server": "^4.2.3",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@tanstack/react-query": "5.64.2",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-email": "^4.2.3",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11",
    "yalc": "^1.0.0-pre.53"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.9.0

### Database and its version

PostgresSQL 15.14

### Operating system name and version

Windows 11

### Browser name

_No response_

### What happended?

This is my model `OrderStatus`, there is a type error when trying to use the methods from its service.

```ts
import { model } from "@medusajs/framework/utils"

const OrderStatus = model.define("order_status", {
  id: model.id().primaryKey(),
  name: model.text(),
  rank: model.number(),
  color: model.text(),
  notifyCustomer: model.boolean().default(false),
  notifyAdmin: model.boolean().default(false)
})

export default OrderStatus
```

The type hints are different from the actual pluralised method because the model name ends with s.

Image 

### Expected behavior

The method and type hints should match.

### Actual behavior

It sticks with `service.createOrderStatus` as the type when in fact the method is `service.createOrderStatuses`.

### Link to reproduction repo

N/A

### PR DESCRIPTION
**Pull request by willbouch**
CLOSES #13234

### CODE REVIEW

File: packages/core/types/src/common/common.ts [hunk 1]
```diff
@@ -380,7 +381,7 @@ export type Pluralize<Singular extends string> =
     : Singular extends `${infer R}is`
     ? `${R}ises`
     : Singular extends `${string}s`
-    ? `${Singular}`
+    ? `${Singular}es`
```
Comment (willbouch) [inline packages/core/types/src/common/common.ts:384]: I want your opinion on this. This is something quickly I did to close the linked issue, but this looks like it might be a breaking change for some people. I could also just specify a custom one for the word `status` and get that merged to close the issue. But this is not sustainable. We need to find a better way for these rules

Comment (adrien2p) [reply packages/core/types/src/common/common.ts:384]: Unfortunately there is many rules I agree, and from a typing perspective not a lot of options to get it out of the box (at least when we done it). Have you checked if the utils is doing it correctly?

**Review by adrien2p — APPROVED** [review]

File: packages/core/types/src/common/common.ts (hunk 1 above)
Comment (willbouch) [reply packages/core/types/src/common/common.ts:384]: What do you mean? If I tested it fixes the issue?

Comment (adrien2p) [reply packages/core/types/src/common/common.ts:384]: I meant, this one is for the typing. But we also generate those runtime method names. Are they good or do we need to do something there?

Comment (willbouch) [reply packages/core/types/src/common/common.ts:384]: You are right, something is missing here and I am not quite sure what. Do you happen to know? Are the "plural functions" supposed to be generated?
CleanShot 2025-09-14 at 21 42 01

Comment (adrien2p) [reply packages/core/types/src/common/common.ts:384]: the method names are built by this util `buildMethodNamesFromModel` which rely on other utils that you can probably look at. Also, for the module service typings, you can look at `AbstractModuleService` where here we prepare the method names for the module service and rely on `ExtractPluralName` which rely on the type util you have changed and should work.
Screenshot 2025-09-15 at 09 11 06

**Comment by bqst** [comment]
@willbouch 
After upgrading to Medusa 2.10.3, I'm experiencing issues with auto-generated method names in custom modules. The problem appears to be related to this PR.

For an entity named DocumentInvoiceSettings, the service should generate methods with names like:
`createDocumentInvoiceSettings`
`listDocumentInvoiceSettings`
`updateDocumentInvoiceSettings`
etc.

TypeScript is now expecting method names with double "s" suffixes:
`createDocumentInvoiceSettingses`
`listDocumentInvoiceSettingses`
`updateDocumentInvoiceSettingses`
etc.

Currently using the incorrectly pluralized method names as suggested by TypeScript, but this feels wrong and may break in future versions.

**Comment by willbouch** [comment]
> @willbouch After upgrading to Medusa 2.10.3, I'm experiencing issues with auto-generated method names in custom modules. The problem appears to be related to this PR.
> 
> For an entity named DocumentInvoiceSettings, the service should generate methods with names like: `createDocumentInvoiceSettings` `listDocumentInvoiceSettings` `updateDocumentInvoiceSettings` etc.
> 
> TypeScript is now expecting method names with double "s" suffixes: `createDocumentInvoiceSettingses` `listDocumentInvoiceSettingses` `updateDocumentInvoiceSettingses` etc.
> 
> Currently using the incorrectly pluralized method names as suggested by TypeScript, but this feels wrong and may break in future versions.

Oh yeah you are right! I'm sorry. We will work on something that is a bit more scalable in the future. This thing has caused too many bugs and quirks

**Comment by willbouch** [comment]
@bqst For now though, I posted a [PR](https://github.com/medusajs/medusa/pull/13558) that will fix your issue as a "bandaid solution"
