### PR TITLE
fix: support search price list

### LINKED ISSUE #1289: [Bug] free text search in price lists causes an error in core
Passing a `q` query param to `GET /admin/price-lists/` cause the following error:

image

This is caused by how we treat the `q` param at the level of the `PriceListService.listAndCount()` method [here](https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/services/price-list.ts#L257). The `q` param should be removed from the `query.where` object. In addition, the presence of the `q` param in the `selector` argument should trigger a query different from the `findAndCount` method of the `PriceListRepository`. You can get inspired from how we do it in the `ProductService` [here](https://github.com/medusajs/medusa/blob/develop/packages/medusa/src/services/product.js#L128-L136), or `DiscountService`, etc.

### PR DESCRIPTION
**Pull request by zakariaelas**
### What 
- fixes #1289 
- adds support for free text search for price lists
- adds a `getFreeTextSearchResultsAndCount` method in the `PriceList` repository
- adds the `findWithRelations` and `findOneWithRelations` methods to the repo (shamelessly copied from other repos 😅 )

### How

- the `getFreeTextSearchResultsAndCount` joins the customer_group table and query the relevant fields (`name`, `description`, `customer_group.name`). It also takes into account the `query.where` object to handle more refined text searches

### Testing

- integration test to make sure querying works with the name and description fields
- integration test to make sure filtering and querying can both work at the same time

### CODE REVIEW

File: packages/medusa/src/repositories/price-list.ts [hunk 1]
```diff
@@ -1,5 +1,111 @@
...
+  EntityRepository,
+  FindManyOptions,
+  FindOperator,
+  OrderByCondition,
+  Repository,
+} from "typeorm"
 import { PriceList } from "../models/price-list"
+import { PriceListStatus, PriceListType } from "../types/price-list"
 
+type CustomOptions = {
```
Comment (olivermrbl) [inline packages/medusa/src/repositories/price-list.ts:13]: suggestion: Extract to util since it seems to be quite generic

Comment (olivermrbl) [reply packages/medusa/src/repositories/price-list.ts:13]:
```
type CustomFindOptions<TModel extends BaseEntity> = {
  select?: FindManyOptions["select"]
  where?: FindManyOptions["where"] & {
    status?: FindOperator<TModel extends BaseEntity>[]
    type?: FindOperator<TModel extends BaseEntity>[]
  }
  order?: OrderByCondition
  skip?: number
  take?: number
} 
```

**Review by olivermrbl — APPROVED** [review]
LGTM! Tiny suggestion. Take it or leave it 😅

File: integration-tests/api/__tests__/admin/price-list.js [hunk 2]
```diff
@@ -211,6 +211,114 @@ describe("/admin/price-lists", () => {
...
+        })
+        .catch((err) => {
+          console.warn(err.response.data)
+        })
+
+      expect(response.status).toEqual(200)
+      expect(response.data.price_lists).toEqual(
+        expect.arrayContaining([
+          expect.objectContaining({
+            name: "VIP winter sale",
```
Comment (adrien2p) [inline integration-tests/api/__tests__/admin/price-list.js:256]: should we check the description here?

File: integration-tests/api/__tests__/admin/price-list.js [hunk 3]
```diff
@@ -211,6 +211,114 @@ describe("/admin/price-lists", () => {
...
+          }),
+        ])
+      )
+      expect(response.data.count).toEqual(1)
+    })
+
+    it("given a wrong search query, returns empty list", async () => {
```
Comment (adrien2p) [inline integration-tests/api/__tests__/admin/price-list.js:263]: it is not really a wrong search query but more that it just does not exists.
I would go with `given a search query, returns empty lists when does not exists` something alongs that line

File: integration-tests/api/__tests__/admin/price-list.js [hunk 4]
```diff
@@ -211,6 +211,114 @@ describe("/admin/price-lists", () => {
...
+        })
+        .catch((err) => {
+          console.warn(err.response.data)
+        })
+
+      expect(response.status).toEqual(200)
+      expect(response.data.price_lists).toEqual(
+        expect.arrayContaining([
+          expect.objectContaining({
+            name: "VIP winter sale",
```
Comment (adrien2p) [inline integration-tests/api/__tests__/admin/price-list.js:316]: should we check the status here.

File: packages/medusa/src/repositories/price-list.ts (hunk 1 above)
Comment (adrien2p) [reply packages/medusa/src/repositories/price-list.ts:13]: I don't think it should go to util but into the type directory in the `common` file.

File: packages/medusa/src/repositories/price-list.ts [hunk 5]
```diff
@@ -1,5 +1,111 @@
...
+  where?: FindManyOptions["where"] & {
+    status?: FindOperator<PriceListStatus>[]
+    type?: FindOperator<PriceListType>[]
+  }
+  order?: OrderByCondition
+  skip?: number
+  take?: number
+}
+
+type FindOptions = CustomOptions
```
Comment (adrien2p) [inline packages/medusa/src/repositories/price-list.ts:24]: why does that type exists? we could directly use the `CustomOptions` instead no?

File: packages/medusa/src/repositories/price-list.ts [hunk 6]
```diff
@@ -1,5 +1,111 @@
...
 @EntityRepository(PriceList)
-export class PriceListRepository extends Repository<PriceList> {}
+export class PriceListRepository extends Repository<PriceList> {
+  public async getFreeTextSearchResultsAndCount(
+    q: string,
+    options: FindOptions = { where: {} },
+    relations: Array<keyof PriceList> = []
+  ): Promise<[PriceList[], number]> {
+    if (!options.where) {
```
Comment (adrien2p) [inline packages/medusa/src/repositories/price-list.ts:32]: `options.where = options.where ?? {}` instead

File: packages/medusa/src/repositories/price-list.ts [hunk 7]
```diff
@@ -1,5 +1,111 @@
...
+  take?: number
+}
+
+type FindOptions = CustomOptions
 @EntityRepository(PriceList)
-export class PriceListRepository extends Repository<PriceList> {}
+export class PriceListRepository extends Repository<PriceList> {
+  public async getFreeTextSearchResultsAndCount(
+    q: string,
+    options: FindOptions = { where: {} },
```
Comment (adrien2p) [inline packages/medusa/src/repositories/price-list.ts:29]: `options: CustomOptions = {}` instead

File: packages/medusa/src/repositories/price-list.ts [hunk 8]
```diff
@@ -1,5 +1,111 @@
...
+    const price_lists = await this.findWithRelations(
+      relations,
+      results.map((r) => r.id)
+    )
+
+    return [price_lists, count]
+  }
+
+  public async findWithRelations(
+    relations: Array<keyof PriceList> = [],
```
Comment (adrien2p) [inline packages/medusa/src/repositories/price-list.ts:60]: `(keyof PriceList)[]` instead

Comment (adrien2p) [reply packages/medusa/src/repositories/price-list.ts:60]: `Array<string>` is good when we want to extends it such that:
```ts
class CustomArray extends Array<string> {}
```

File: packages/medusa/src/repositories/price-list.ts [hunk 9]
```diff
@@ -1,5 +1,111 @@
...
+      | Omit<FindManyOptions<PriceList>, "relations">
+      | string[] = {}
+  ): Promise<PriceList[]> {
+    let entities
+    if (Array.isArray(idsOrOptionsWithoutRelations)) {
+      entities = await this.findByIds(idsOrOptionsWithoutRelations)
+    } else {
+      entities = await this.find(idsOrOptionsWithoutRelations)
+    }
+    const entitiesIds = entities.map(({ id }) => id)
```
Comment (adrien2p) [inline packages/medusa/src/repositories/price-list.ts:71]: a variable should always be declared as close as possible from where it is used, here it should be declared line 82. I will not mention other places where I see that, if you could have a look please.

File: packages/medusa/src/repositories/price-list.ts [hunk 10]
```diff
@@ -1,5 +1,111 @@
...
+
+    const groupedRelations = {}
+    for (const rel of relations) {
```
Comment (adrien2p) [inline packages/medusa/src/repositories/price-list.ts:74]: `for (const relation of relations)` just for a good naming convention if we could just singularised it would be nice for readability

File: packages/medusa/src/repositories/price-list.ts [hunk 11]
```diff
@@ -1,5 +1,111 @@
...
+      const [topLevel] = rel.split(".")
+      if (groupedRelations[topLevel]) {
+        groupedRelations[topLevel].push(rel)
+      } else {
+        groupedRelations[topLevel] = [rel]
+      }
+    }
+
+    const entitiesIdsWithRelations = await Promise.all(
+      Object.entries(groupedRelations).map(([_, rels]) => {
```
Comment (adrien2p) [inline packages/medusa/src/repositories/price-list.ts:84]: `Object.values(groupedRelations).map((relations: string[]) => ...)` instead since we do not use the key

File: packages/medusa/src/repositories/price-list.ts [hunk 12]
```diff
@@ -1,5 +1,111 @@
...
+        return this.findByIds(entitiesIds, {
+          select: ["id"],
+          relations: rels as string[],
+        })
+      })
+    ).then(flatten)
```
Comment (adrien2p) [inline packages/medusa/src/repositories/price-list.ts:90]: We can use the native way of flattening as follow
```ts
.then(entitiesIdsWithRelations => entitiesIdsWithRelations.flat(Infinity))
```

File: packages/medusa/src/repositories/price-list.ts [hunk 13]
```diff
@@ -1,5 +1,111 @@
...
+    const entitiesAndRelations = entitiesIdsWithRelations.concat(entities)
+
+    const entitiesAndRelationsById = groupBy(entitiesAndRelations, "id")
+    return map(entitiesAndRelationsById, (entityAndRelations) =>
+      this.merge({} as PriceList, ...entityAndRelations)
```
Comment (adrien2p) [inline packages/medusa/src/repositories/price-list.ts:95]: `this.merge(this.create(), ...entityAndRelations)` what do you think? instead of casting? otherwise the consumer could be misled by receiving what he think is a PriceList but instead there is some missing properties since it is not really.

File: packages/medusa/src/repositories/price-list.ts [hunk 14]
```diff
@@ -1,5 +1,111 @@
...
+    )
+  }
+
+  public async findOneWithRelations(
+    relations: Array<keyof PriceList> = [],
```
Comment (adrien2p) [inline packages/medusa/src/repositories/price-list.ts:100]: `(keyof PriceList)[]`

File: packages/medusa/src/repositories/price-list.ts [hunk 15]
```diff
@@ -1,5 +1,111 @@
...
+    optionsWithoutRelations: Omit<FindManyOptions<PriceList>, "relations"> = {}
```
Comment (adrien2p) [inline packages/medusa/src/repositories/price-list.ts:101]: I think generally speaking, this argument could be just called options, otherwise it can become very difficult to describe depending the omit etc.

File: packages/medusa/src/repositories/price-list.ts [hunk 16]
```diff
@@ -1,5 +1,111 @@
...
+  ): Promise<PriceList> {
+    optionsWithoutRelations.take = 1
+
+    const result = await this.findWithRelations(
+      relations,
+      optionsWithoutRelations
+    )
+    return result[0]
```
Comment (adrien2p) [inline packages/medusa/src/repositories/price-list.ts:109]: what happen if there is no result there?
I think we could go for 
```ts
return (await this.findWithRelations(
    relations,
    optionsWithoutRelations
))?.pop()
```

wdyt?

File: packages/medusa/src/services/price-list.ts [hunk 17]
```diff
@@ -253,9 +253,21 @@ class PriceListService extends BaseService {
...
   ): Promise<[PriceList[], number]> {
     const priceListRepo = this.manager_.getCustomRepository(this.priceListRepo_)
-
-    const query = this.buildQuery_(selector, config)
-    return await priceListRepo.findAndCount(query)
+    const q = selector.q
+    const { relations, ...query } = this.buildQuery_(selector, config)
+
+    if (q) {
+      delete query.where.q
```
Comment (adrien2p) [inline packages/medusa/src/services/price-list.ts:260]: `query.where.q = undefined` ? for the same reasons describe earlier

File: packages/medusa/src/services/price-list.ts [hunk 18]
```diff
@@ -253,9 +253,21 @@ class PriceListService extends BaseService {
...
+      const resultsWithCount =
+        await priceListRepo.getFreeTextSearchResultsAndCount(
+          q,
+          query,
+          relations
+        )
+
+      return resultsWithCount
```
Comment (adrien2p) [inline packages/medusa/src/services/price-list.ts:268]: `return await priceListRepo.getFreeTextSearchResultsAndCount(...)` the variable is redundant

File: packages/medusa/src/repositories/price-list.ts (hunk 1 above)
Comment (zakariaelas) [reply packages/medusa/src/repositories/price-list.ts]: Pushed a fix, but still need your opinion on it @adrien2p, it looks like this: 
```typescript
export interface CustomFindOptions<TModel, InKeys extends keyof TModel> {
  select?: FindManyOptions<TModel>["select"]
  where?: FindManyOptions<TModel>["where"] &
    {
      [P in InKeys]?: TModel[P][]
    }
  order?: OrderByCondition
  skip?: number
  take?: number
}
```

We can't really have 100% of what @olivermrbl suggested because the `status` and `type` fields are specific to the `PriceList` entity, but it seems like what we usually do is override some properties' type(s) by an array to later implement a logical "OR" or "IN" (i.e: get the price lists with type "override" OR "sale"). That's why I added another generic to the type so that consumers of the type specify which property(ies) be augmented as array

File: packages/medusa/src/repositories/price-list.ts (hunk 8 above)
Comment (zakariaelas) [reply packages/medusa/src/repositories/price-list.ts:47]: Thanks for the comment! Any downsides with the latter approach (using `Array`)?

File: packages/medusa/src/repositories/price-list.ts (hunk 1 above)
Comment (adrien2p) [reply packages/medusa/src/repositories/price-list.ts]: Nice job @zakariaelas it looks good to me if I have properly understood the needs 😀

File: packages/medusa/src/repositories/price-list.ts (hunk 8 above)
Comment (adrien2p) [reply packages/medusa/src/repositories/price-list.ts]: It is more to keep it consistent across the code base 😅

File: packages/medusa/src/repositories/price-list.ts (hunk 16 above)
Comment (adrien2p) [reply packages/medusa/src/repositories/price-list.ts:94]: I dont think we should return PriceList | [] since it is a result vs an array of result, the common behaviour of a find method is to return the result or undefined. Wdyt?

File: packages/medusa/src/services/price-list.ts (hunk 17 above)
Comment (adrien2p) [reply packages/medusa/src/services/price-list.ts:260]: From a perf point of view, setting a property to undefined is more performant than deleting the property which mutate the object structure 😅
Dont know if it make sense. Here some explanation https://levelup.gitconnected.com/5-facts-about-delete-operator-in-javascript-c16fd2588cd?gi=4c1668543b9a

But in the end it really depends on the context so the choice is up to you since it is a micro opti here 😂

File: packages/medusa/src/repositories/price-list.ts [hunk 19]
```diff
@@ -1,5 +1,96 @@
...
+    
+    const entitiesIds = entities.map(({ id }) => id)
+    const entitiesIdsWithRelations = await Promise.all(
+      Object.values(groupedRelations).map((relations: string[]) => {
+        return this.findByIds(entitiesIds, {
+          select: ["id"],
+          relations: relations as string[],
+        })
+      })
+    ).then(entitiesIdsWithRelations => entitiesIdsWithRelations.flat())
```
Comment (adrien2p) [inline packages/medusa/src/repositories/price-list.ts:75]: Careful, the flat method only flatten the number of level specified. If none then it flatten one level, is that the intended behaviour ? Just to be sure 😅

**Comment by adrien2p** [comment]
@zakariaelas small suestion/need attention point, other than that its looking great for me 🍾 nice job

File: packages/medusa/src/repositories/price-list.ts (hunk 16 above)
Comment (zakariaelas) [reply packages/medusa/src/repositories/price-list.ts:94]: totally .. I just re-read what I wrote, for some reason I thought we were talking about the `findWithRelations` method 🤦‍♂️  .. you're completely right 😆

File: packages/medusa/src/repositories/price-list.ts (hunk 19 above)
Comment (zakariaelas) [reply packages/medusa/src/repositories/price-list.ts:75]: I think so. Before the requested change, we passed lodash's [flatten](https://lodash.com/docs/4.17.15#flatten) which also flattens a single level, hence why I used `flat` with the default argument. Also from my understanding, I don't think we'll exceed 1 level of depth no?

File: packages/medusa/src/services/price-list.ts (hunk 17 above)
Comment (zakariaelas) [reply packages/medusa/src/services/price-list.ts:260]: Interesting! Thanks for sharing, I didn't know that 😄 

Personally, if perf is not a problem currently, I prefer the `delete` operator mostly because then we don't have to worry about the property lurking in case someone uses the object in a `for .. in` loop, but you might have a counter argument for this one, so please feel free to disagree and share!

File: packages/medusa/src/repositories/price-list.ts (hunk 19 above)
Comment (adrien2p) [reply packages/medusa/src/repositories/price-list.ts:75]: We shouldn't indeed, but just wanted to be sure I al not missing something 🤣

**Review by adrien2p — APPROVED** [review]
