### PR TITLE
fix(utils): Typecasting non-text fields in FTS

### LINKED ISSUE #12718: [Bug]: Cannot search orders by display id or relations searcahable properties
### Package.json file

```JSON
{
  "name": "medusa",
  "version": "0.0.0",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "reindex": "medusa exec ./src/scripts/reindex-meilisearch.ts",
    "start": "medusa start",
    "dev": "medusa develop & pnpm -C ./../../packages/medusa-admin-tlc run dev",
    "predeploy": "medusa db:migrate",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@ariakit/react": "^0.4.17",
    "@aws-sdk/client-s3": "^3.825.0",
    "@aws-sdk/s3-request-presigner": "^3.825.0",
    "@dnd-kit/core": "^6.3.1",
    "@dnd-kit/sortable": "^10.0.0",
    "@hookform/error-message": "^2.0.1",
    "@hookform/resolvers": "3.4.2",
    "@medusajs/admin-sdk": "^2.8.4",
    "@medusajs/cli": "^2.8.4",
    "@medusajs/dashboard": "workspace:^",
    "@medusajs/framework": "^2.8.4",
    "@medusajs/icons": "^2.8.4",
    "@medusajs/js-sdk": "^2.8.4",
    "@medusajs/medusa": "^2.8.4",
    "@medusajs/types": "^2.8.4",
    "@medusajs/ui": "^4.0.14",
    "@mikro-orm/core": "6.4.3",
    "@mikro-orm/knex": "6.4.3",
    "@mikro-orm/migrations": "6.4.3",
    "@mikro-orm/postgresql": "6.4.3",
    "@radix-ui/react-popover": "^1.1.14",
    "@tanstack/react-table": "^8.21.3",
    "@tanstack/react-virtual": "^3.13.9",
    "awilix": "^8.0.1",
    "date-fns": "^4.1.0",
    "i18next": "^25.2.1",
    "i18next-browser-languagedetector": "^8.1.0",
    "json-2-csv": "^5.5.4",
    "lodash": "^4.17.21",
    "match-sorter": "^8.0.2",
    "meilisearch": "^0.49.0",
    "multer": "^1.4.5-lts.1",
    "pg": "^8.16.0",
    "radix-ui": "^1.4.2",
    "react-currency-input-field": "^3.10.0",
    "react-hook-form": "^7.57.0",
    "react-i18next": "^15.5.2",
    "react-quill": "^2.0.0",
    "vitest": "^3.2.2",
    "zod": "3.22.4"
  },
  "devDependencies": {
    "@faker-js/faker": "^9.8.0",
    "@medusajs/test-utils": "^2.8.4",
    "@mikro-orm/cli": "6.4.3",
    "@radix-ui/react-label": "^2.1.7",
    "@radix-ui/react-slot": "^1.2.3",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.37",
    "@tanstack/react-query": "5.64.2",
    "@types/jest": "^29.5.14",
    "@types/multer": "^1.4.12",
    "@types/node": "^20.19.0",
    "@types/react": "^18.3.23",
    "@types/react-dom": "^18.3.7",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.8.3",
    "vite": "^5.4.19",
    "zod": "3.22.4"
  },
  "peerDependencies": {
    "react-router-dom": "6.20.1"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22

### Database and its version

Postgres 17

### Operating system name and version

Alpine Linux

### Browser name

_No response_

### What happended?

Opened the admin dashboard, go to Orders, try to search on a display ID, phone number or address information (city, postal code, etc.) no orders are found.

### Expected behavior

Find orders by details of the order itself and its relations.

### Actual behavior

No orders are found on more detailed order information or any relations' searchable properties.

### Link to reproduction repo

N/A

### PR DESCRIPTION
**Pull request by olivermrbl**
### What

Fix the typecasting for non-text properties in our FTS

### Why

Currently, the `::text` casting is considered part of the column name leading to the following error (in the case of orders):
```
column o0.display_id::text does not exist
```

### How

Use raw typecasting flavor introduced in MikroORM v6

https://github.com/mikro-orm/mikro-orm/discussions/4774#discussioncomment-7165490

----
Separately, this PR also adds support for defining the `autoincrement` modifier as searchable.

### CODE REVIEW

**Comment by olivermrbl** [comment]
@adrien2p, let me know if this makes sense.

**Review by adrien2p — APPROVED** [review]
Yes I think it make sense to have

File: packages/core/utils/src/dml/properties/autoincrement.ts [hunk 1]
```diff
@@ -8,7 +8,10 @@ import { PrimaryKeyModifier } from "./primary-key"
 export class AutoIncrementProperty extends BaseProperty<number> {
   protected dataType: {
     name: "serial"
-    options: {}
+    options: {
+      searchable?: boolean
+      primaryKey?: boolean
```
Comment (adrien2p) [inline packages/core/utils/src/dml/properties/autoincrement.ts:13]: Q: is threre a reason for adding this option pk here?

Comment (olivermrbl) [reply packages/core/utils/src/dml/properties/autoincrement.ts:13]: Without it, there will be a type error on line 62, because the type of `options` in the constructor doesn't mat the type of `options` in the `dataType`.

**Comment by juanzgc** [comment]
Related SUP-1838
