### PR TITLE
fix(core-flows, medusa): Prevent cart addresses duplication on update

### LINKED ISSUE #12966: [Bug]:  Invalid field error when updating shipping_address via cart update API
### Package.json file

```JSON
{
  "name": "nuxt-app",
  "type": "module",
  "private": true,
  "scripts": {
    "build": "nuxt build",
    "dev": "nuxt dev --port 50526",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "lint": "eslint ."
  },
  "dependencies": {
    "@deeptimes/fapro": "^0.6.7",
    "@fontsource-variable/roboto": "^5.2.6",
    "@fontsource/roboto": "^5.2.6",
    "@medusajs/js-sdk": "^2.8.6",
    "@medusajs/types": "^2.8.6",
    "@nuxt/fonts": "0.11.4",
    "@nuxt/icon": "1.13.0",
    "@nuxt/image": "^1.10.0",
    "@nuxt/kit": "^3.17.6",
    "@nuxt/scripts": "0.11.7",
    "@nuxtjs/device": "^3.2.4",
    "@nuxtjs/medusa": "1.1.0",
    "@primevue/forms": "^4.3.6",
    "@tailwindcss/vite": "^4.1.11",
    "@unhead/vue": "^2.0.12",
    "@vee-validate/nuxt": "^4.15.1",
    "@vee-validate/zod": "^4.15.1",
    "axios": "^1.10.0",
    "canvas-confetti": "^1.9.3",
    "floating-vue": "^5.2.2",
    "nuxt": "^3.17.6",
    "nuxt-swiper": "2.0.1",
    "nuxt-zod-i18n": "^1.12.0",
    "pinia-plugin-persistedstate": "^4.4.1",
    "primevue": "^4.3.6",
    "swiper": "^11.2.10",
    "tailwind-merge": "^3.3.1",
    "tailwindcss": "^4.1.11",
    "tailwindcss-primeui": "^0.6.1",
    "vue": "^3.5.17",
    "vue-router": "^4.5.1",
    "zod": "^3.25.74"
  },
  "devDependencies": {
    "@antfu/eslint-config": "^4.16.2",
    "@iconify-json/flag": "^1.2.6",
    "@iconify-json/lucide": "^1.2.55",
    "@nuxtjs/color-mode": "^3.5.2",
    "@nuxtjs/i18n": "^9.5.6",
    "@pinia/nuxt": "^0.11.1",
    "@primevue/nuxt-module": "^4.3.6",
    "@tailwindcss/typography": "^0.5.16",
    "@types/canvas-confetti": "^1.9.0",
    "@types/node": "^22.16.0",
    "@vueuse/core": "^13.5.0",
    "@vueuse/nuxt": "^13.5.0",
    "eslint": "^9.30.1",
    "pinia": "^3.0.3",
    "sass-embedded": "^1.89.2",
    "tsx": "^4.20.3",
    "typescript": "^5.8.3"
  }
}
```

### Node.js version

v21.00

### Database and its version

PostgreSQL 17

### Operating system name and version

macos

### Browser name

chrome

### What happended?

I'm encountering an issue when trying to update the shipping_address through the cart update API endpoint /store/carts/{id}. According to the documentation, when updating an address, the id field should be included, while omitting the id creates a new address. However, when I include the id in my request payload, I receive an "Invalid request" error.

Image

Due to this issue, I'm forced to omit the id field from the request, which results in creating a new address record every time I update the cart instead of updating the existing one. This leads to unnecessary address duplication in the system.

### Expected behavior

The cart's shipping address should be updated successfully when the id field is provided, as stated in the documentation.

### Actual behavior

The API returns an error message:
```
message: "Invalid request: Unrecognized fields: 'id'"
```

I'm unsure if this is a bug in the API implementation or if I'm using the endpoint incorrectly. Could you please clarify the correct way to update shipping addresses via the cart update API?

### Link to reproduction repo

https://docs.medusajs.com/api/store#carts_postcartsid

### PR DESCRIPTION
**Pull request by NicolasGorga**
## Summary

**What** — What changes are introduced in this PR?

Prevent `shipping_address` and `billing_address` recreation when updating a cart through the corresponding store endpoint.

**Why** — Why are these changes relevant or necessary?  

Without this, there is no way to keep a previosuly created shipping or billing address when updating fields from them or the cart in a checkout flow, so any time it is updated, these get recreated causing duplication.

**How** — How have these changes been implemented?

Extended the validator from the store update cart endpoint, to allow to pass `shipping_address.id` and `billing_address.id`, aligning it with the `updateCartWorkflow` input. The repository then uses this id to keep the foreign key reference unchanged.

This by itself doesn't allow one to update the addresses fields from this endpoint, which is needed in a checkout from where the customer can update specific fields from the address after saving it the first time they move to the shipping step. I'be also inlcuded inside the `updateCartsStep` logic to update the addresses fields.

**Testing** — How have these changes been tested, or how can the reviewer test the feature?

Included tests inside the cart module integration-tests and also made tests at runtime form a tests project and storefront to validate faster.

---

## Examples

Provide examples or code snippets that demonstrate how this feature works, or how it can be used in practice.  
This helps with documentation and ensures maintainers can quickly understand and verify the change.

```ts
// Example usage
```

---

## Checklist

Please ensure the following before requesting a review:

- [x] I have added a **changeset** for this PR
    - Every non-breaking change should be marked as a **patch**
    - To add a changeset, run `yarn changeset` and follow the prompts
- [x] The changes are covered by relevant **tests**
- [x] I have verified the code works as intended locally
- [x] I have linked the related issue(s) if applicable

---

## Additional Context

Add any additional context, related issues, or references that might help the reviewer understand this PR.

Fixes #12966
closes CORE-1254

---

> [!NOTE]
> Enables updating existing cart shipping/billing addresses by accepting `id` in the store update-cart validator and updating nested address fields in `update-carts` with rollback support, plus tests.
> 
> - **Core Flows**:
>   - Update `update-carts` step to update nested address fields when `shipping_address.id`/`billing_address.id` is provided.
>   - Capture pre-update `carts` and `addresses` and add compensation to restore them on failure.
> - **API (Store)**:
>   - Extend `packages/medusa/src/api/store/carts/validators.ts` to accept `id` in `shipping_address` and `billing_address` for `UpdateCart`.
> - **Tests**:
>   - Add integration tests for updating shipping/billing addresses (individually and together) and rollback behavior in `integration-tests/modules/__tests__/cart/store/cart.workflows.spec.ts`.
> - **Changeset**:
>   - Patch releases for `@medusajs/core-flows` and `@medusajs/medusa`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 31cfb39d46ec8fae27f533064099d55326e0013d. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/core/core-flows/src/cart/steps/update-carts.ts [hunk 1]
```diff
@@ -46,17 +47,41 @@ export const updateCartsStep = createStep(
       { select: selects, relations }
     )
 
+	// Since service factory udpate method will correctly keep the reference to the addresses,
+	// but won't update its fields, we do this separately
+	const addressesInput = data.flatMap(cart => [cart.shipping_address, cart.billing_address])
+		.filter(address => !!address)
+	const addressesToUpdate = addressesInput.map(address => 'id' in address ? address : null)
```
Comment (willbouch) [inline packages/core/core-flows/src/cart/steps/update-carts.ts]: Why not just run a filter? The map looks useless to me or am I missing something?
`addressesInput.filter(address => "id" in address)`

Comment (NicolasGorga) [reply packages/core/core-flows/src/cart/steps/update-carts.ts]: @willbouch You are totally right, removed it!

**Comment by NicolasGorga** [comment]
@willbouch think this would be a good one to include in next release wyt?

File: packages/core/core-flows/src/cart/steps/update-carts.ts [hunk 2]
```diff
@@ -46,17 +47,40 @@ export const updateCartsStep = createStep(
...
     )
 
+	// Since service factory udpate method will correctly keep the reference to the addresses,
+	// but won't update its fields, we do this separately
+	const addressesInput = data.flatMap(cart => [cart.shipping_address, cart.billing_address])
+		.filter(address => !!address)
+	const addressesToUpdate = addressesInput.filter(address => "id" in address)
+	const addressesBeforeUpdate = await cartModule.listAddresses(
+		{ id: addressesToUpdate.map(address => address.id as string)}
+	)
```
Comment (adrien2p) [inline packages/core/core-flows/src/cart/steps/update-carts.ts]:
```suggestion
let addressesToUpdateIds: string[] = []
    const addressesToUpdate = addressesInput.filter(
      (address): address is UpdateAddressDTO => {
        if ("id" in address && !!address.id) {
          addressesToUpdateIds.push(address.id as string)
          return true
        }
        return false
      }
    )
    const addressesBeforeUpdate = await cartModule.listAddresses({
      id: addressesToUpdate.map((address) => address.id),
    })
```

File: packages/core/core-flows/src/cart/steps/update-carts.ts [hunk 3]
```diff
@@ -46,17 +47,40 @@ export const updateCartsStep = createStep(
...
+	if (addressesToUpdate.length) {
+		await cartModule.updateAddresses(addressesToUpdate as unknown as UpdateAddressDTO[])
```
Comment (adrien2p) [inline packages/core/core-flows/src/cart/steps/update-carts.ts]: with the suggestion above, you shouldnt have to cast anymore

Comment (NicolasGorga) [reply packages/core/core-flows/src/cart/steps/update-carts.ts]: Nice!

File: packages/core/core-flows/src/cart/steps/update-carts.ts (hunk 2 above)
Comment (NicolasGorga) [reply packages/core/core-flows/src/cart/steps/update-carts.ts]: Like it.

**Review by adrien2p — APPROVED** [review]

File: packages/core/core-flows/src/cart/steps/update-carts.ts [hunk 4]
```diff
@@ -46,17 +47,53 @@ export const updateCartsStep = createStep(
       { select: selects, relations }
     )
 
+    // Since service factory udpate method will correctly keep the reference to the addresses,
+    // but won't update its fields, we do this separately
+    const addressesInput = data
```
Comment (fPolic) [inline packages/core/core-flows/src/cart/steps/update-carts.ts:52]: discussion(non-blocking): should we push this logic to the service method? Seems like internal responsibility, and also a pattern that we use in other modules.
Alternatively, maybe using the `upsert` method here in the update step as we do for product update, which should upsert the shipping addresses correctly when the ID is passed.

File: packages/core/core-flows/src/cart/steps/update-carts.ts [hunk 5]
```diff
@@ -46,17 +47,53 @@ export const updateCartsStep = createStep(
...
+      .flatMap((cart) => [cart.shipping_address, cart.billing_address])
+      .filter((address) => !!address)
+    let addressesToUpdateIds: string[] = []
+    const addressesToUpdate = addressesInput.filter(
+      (address): address is UpdateAddressDTO => {
+        if ("id" in address && !!address.id) {
```
Comment (fPolic) [inline packages/core/core-flows/src/cart/steps/update-carts.ts:58]: nit:  `if (!!address.id) {`

**Review by fPolic — COMMENTED** [review]
LGTM overall, we just need the test to pass, left a discussion point

File: packages/core/core-flows/src/cart/steps/update-carts.ts (hunk 5 above)
Comment (NicolasGorga) [reply packages/core/core-flows/src/cart/steps/update-carts.ts:58]: I have to assert it like that for typescript not to complain in `!!address.id` since id is not present in `CreateAddressDTO`
