### PR TITLE
fix(create-medusa-app): --db-url keep asking db credentials

### LINKED ISSUE #11033: it keeps asking for the database credentials even after specifying --db-url
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

when running `npx create-medusa-app@latest --db-url "url"` it keeps asking for the database credentials and keeps failing

### How can this issue be resolved?

1.
2.
3.
...

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

### PR DESCRIPTION
**Pull request by Gederooney**
issue #11033: it keeps asking for the database credentials even after specifying --db-url #11033

fix: dbName is always define. Checking for dbName first in getDbClientAndCredentials() was always skiping getForDbUrl case

### CODE REVIEW

File: packages/cli/create-medusa-app/src/utils/project-creator/medusa-project-creator.ts [hunk 1]
```diff
@@ -111,6 +110,8 @@ export class MedusaProjectCreator
         dbUrl: this.options.dbUrl,
         verbose: this.options.verbose,
       })
+    
+
```
Comment (shahednasser) [inline packages/cli/create-medusa-app/src/utils/project-creator/medusa-project-creator.ts]: Can you remove these new lines?

File: packages/cli/create-medusa-app/src/utils/project-creator/medusa-project-creator.ts [hunk 2]
```diff
@@ -44,7 +44,6 @@ export class MedusaProjectCreator
 
   async create(): Promise<void> {
     track("CREATE_CLI_CMA")
-
```
Comment (shahednasser) [inline packages/cli/create-medusa-app/src/utils/project-creator/medusa-project-creator.ts]: Can you remove this change?

**Review by shahednasser — CHANGES_REQUESTED** [review]
Thank you for your contribution! Can I get you to also run `yarn changeset` in the monorepo root and choose a `patch` version update for `create-medusa-app`?

File: packages/cli/create-medusa-app/src/utils/project-creator/medusa-project-creator.ts (hunk 1 above)
Comment (Gederooney) [reply packages/cli/create-medusa-app/src/utils/project-creator/medusa-project-creator.ts]: yes, i did now

File: packages/cli/create-medusa-app/src/utils/project-creator/medusa-project-creator.ts (hunk 2 above)
Comment (Gederooney) [reply packages/cli/create-medusa-app/src/utils/project-creator/medusa-project-creator.ts]: did this as well

**Review by shahednasser — APPROVED** [review]
LGTM thanks!
