### PR TITLE
fix(dashboard,region): fix currency code unset when updating region

### LINKED ISSUE #15226: [Bug]: Region currency_code is cleared when adding a country or metadata
### Package.json file

```JSON
{
  "name": "store",
  
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop --port 9000 --host ecommerce.xxxx.local",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@aws-sdk/client-ses": "^3.1031.0",
    "@aws-sdk/client-sns": "^3.1020.0",
    "@medusajs/admin-sdk": "2.13.6",
    "@medusajs/cli": "2.14.1",
    "@medusajs/file-s3": "2.14.1",
    "@medusajs/framework": "2.14.1",
    "@medusajs/medusa": "2.14.1",
    "axios": "^1.13.4",
    "cloudevents": "^10.0.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.14.1",
    "@swc/core": "^1.7.28",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.12.11",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.4.14",
    "yalc": "^1.0.0-pre.53"
  },
  "engines": {
    "node": ">=20"
  },
  "packageManager": "yarn@1.22.22"
}
```

### Node.js version

v20.19.2

### Database and its version

Postgre 15

### Operating system name and version

N/A — server-side / admin UI bug, not OS-specific

### Browser name

_No response_

### What happended?

When editing a region in the admin dashboard, the `currency_code` field is reset to an empty value when:
- Adding a country to the region, **or**
- Adding/editing a metadata entry on the region

### Steps to reproduce
1. Go to **Settings → Regions** in the admin dashboard
2. Open an existing region that has a `currency_code` set
3. Add a country to the region **or** add a metadata key/value
4. Save the changes
5. Observe that `currency_code` is now empty on the region

### Expected behavior

Adding a country or metadata to a region should preserve the existing `currency_code` — it should remain unchanged after saving.

### Actual behavior

The `currency_code` is cleared/set to empty after saving. Downgrading to **2.13.6** resolves the issue.

### Link to reproduction repo

N/A — bug appears both locally and in production

### PR DESCRIPTION
**Pull request by shahednasser**
## Summary

**What** — What changes are introduced in this PR?

Fix currency code being unset when updating region

Closes #15226

**Why** — Why are these changes relevant or necessary?  

Recent change to currency code normalization lead to setting currency code of a region to an empty string when currency code is not passed. This also was unhandled in the dashboard, leading to a broken dashboard when updating the region and the currency code is removed

**How** — How have these changes been implemented?

- dashboard: Add optional access to country on region
- region: only update currency code when it's set

**Testing** — How have these changes been tested, or how can the reviewer test the feature?

---

## Examples

Provide examples or code snippets that demonstrate how this feature works, or how it can be used in practice.  
This helps with documentation and ensures maintainers can quickly understand and verify the change.

```ts
// Example usage
```

---

## Checklist

Please ensure the following before requesting a review:

- [x] I have added a **changeset** for this PR
    - Every non-breaking change should be marked as a **patch**
    - To add a changeset, run `yarn changeset` and follow the prompts
- [ ] The changes are covered by relevant **tests**
- [x] I have verified the code works as intended locally
- [ ] I have linked the related issue(s) if applicable

---

## Additional Context

Add any additional context, related issues, or references that might help the reviewer understand this PR.

### CODE REVIEW

File: packages/admin/dashboard/src/lib/client/client.ts [hunk 1]
```diff
@@ -1,8 +1,8 @@
 import Medusa from "@medusajs/js-sdk"
 
 export const backendUrl = __BACKEND_URL__ ?? "/"
-const authType = __AUTH_TYPE__ ?? "session"
-const jwtTokenStorageKey = __JWT_TOKEN_STORAGE_KEY__ || undefined
+const authType = "session"
+const jwtTokenStorageKey = undefined
```
Comment (NicolasGorga) [inline packages/admin/dashboard/src/lib/client/client.ts]: I understand this, since it's something I find quite annoying when doing dev work for dashboard running the standalone dev server, without the admin-bundler, which sets these keys, but doing this won't allow to control these configurations via env variables: `ADMIN_AUTH_TYPE` and `ADMIN_JWT_TOKEN_STORAGE_KEY` respectively

**Review by NicolasGorga — CHANGES_REQUESTED** [review]

File: packages/admin/dashboard/src/lib/client/client.ts (hunk 1 above)
Comment (shahednasser) [reply packages/admin/dashboard/src/lib/client/client.ts]: Oops That shouldn't have made it in there 😅, I reverted it now

**Review by NicolasGorga — APPROVED** [review]
LGTM
