### PR TITLE
fix(medusa): Add totals when retrieving order by cart id

### LINKED ISSUE #3773: [v1.8] /store/orders/cart/{cart_id} does not return totals (used to in 1.7)
This API: https://docs.medusajs.com/api/store#tag/Orders/operation/GetOrdersOrderCartId

Is used often to show a confirmation page and in previous version it used to return totals of the cart, but now does not return totals. Can we please fix this so it behaves like it used to? Or provide an `expand` property where totals can be loaded?

### PR DESCRIPTION
**Pull request by olivermrbl**
Resolves CORE-1320
Fixes #3773

### CODE REVIEW

File: packages/medusa/src/services/order.ts [hunk 1]
```diff
@@ -487,35 +487,43 @@ class OrderService extends TransactionBaseService {
     cartId: string,
     config: FindConfig<Order> = {}
   ): Promise<Order> {
-    const orderRepo = this.activeManager_.withRepository(this.orderRepository_)
+    if (!isDefined(cartId)) {
```
Comment (adrien2p) [inline packages/medusa/src/services/order.ts:490]: suggestion: We could have a `retrieve_` method and then the retrieve, retrieveBy* etc calling that retrieve_ method in order to centralize the code as it is the same except for the retrieval condition. This is something we already do here and there. not necessarily in that pr but just to share my thoughts

Comment (olivermrbl) [reply packages/medusa/src/services/order.ts:490]: Yes good idea, I will add it to our backlog.
