### PR TITLE
fix(order): item relation loading in select-in path

### LINKED ISSUE #14628: [Bug]: Order list in admin shows only shipping total instead of full order total (item totals are zero)
### Package.json file

```JSON
{
	"name": "busbasisberlin",
	"version": "0.0.1",
	"description": "A starter for Medusa projects.",
	"author": "Medusa (https://medusajs.com)",
	"license": "MIT",
	"keywords": [
		"sqlite",
		"postgres",
		"typescript",
		"ecommerce",
		"headless",
		"medusa"
	],
	"scripts": {
		"build": "medusa build",
		"seed": "medusa exec ./src/scripts/seed.ts",
		"start": "medusa start",
		"dev": "medusa develop",
		"dev:email": "email dev --dir ./src/modules/resend/emails",
		"predeploy": "medusa db:migrate",
		"docker:up": "docker compose up --build -d",
		"docker:down": "docker compose down",
		"docker:logs": "docker compose logs -f",
		"docker:restart": "docker compose restart",
		"docker:clean": "docker compose down -v && docker system prune -f",
		"deploy": "./scripts/deploy.sh deploy",
		"deploy:rollback": "./scripts/deploy.sh rollback",
		"deploy:status": "./scripts/deploy.sh status",
		"health:check": "./scripts/health-check.sh check",
		"health:wait": "./scripts/health-check.sh wait",
		"bluegreen:setup": "docker compose -f docker-compose.base.yml up -d",
		"bluegreen:blue": "docker compose -f docker-compose.base.yml -f docker-compose.blue.yml up -d --build",
		"bluegreen:green": "docker compose -f docker-compose.base.yml -f docker-compose.green.yml up -d --build",
		"domain:setup": "./scripts/setup-domain.sh",
		"deploy:domain": "./scripts/deploy-with-domain.sh",
		"test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
		"test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
		"test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
		"lint": "eslint \"{src,apps,libs,test}/**/*.ts\" --fix",
		"lint:check": "eslint \"{src,apps,libs,test}/**/*.ts\"",
		"format": "prettier --write \"src/**/*.ts\"",
		"format:check": "prettier --check \"src/**/*.ts\"",
		"import:suppliers": "medusa exec ./src/scripts/import-suppliers.ts",
		"update:suppliers": "medusa exec ./src/scripts/update-suppliers.ts",
		"import:images": "medusa exec ./src/scripts/upload-images.ts",
		"import:products": "medusa exec ./src/scripts/import-products.ts",
		"cleanup:database": "medusa exec ./src/scripts/cleanup-database.ts",
		"meilisearch:import": "medusa exec ./src/scripts/meilisearch-import.ts"
	},
	"dependencies": {
		"@aws-sdk/client-s3": "^3.859.0",
		"@hello-pangea/dnd": "^16.6.0",
		"@medusajs/admin-sdk": "^2.13.0",
		"@medusajs/cli": "^2.13.0",
		"@medusajs/framework": "^2.13.0",
		"@medusajs/index": "^2.13.0",
		"@medusajs/medusa": "^2.13.0",
		"@medusajs/ui": "^4.1.0",
		"@meilisearch/instant-meilisearch": "^0.28.0",
		"@mikro-orm/core": "6.4.16",
		"@mikro-orm/knex": "6.4.16",
		"@mikro-orm/migrations": "6.4.16",
		"@mikro-orm/postgresql": "6.4.16",
		"@react-email/components": "0.3.2",
		"@types/cors": "^2.8.19",
		"@types/puppeteer": "^5.4.7",
		"ajv": "^8.17.1",
		"awilix": "^8.0.1",
		"axios": "^1.10.0",
		"cors": "^2.8.5",
		"csv-parse": "^5.6.0",
		"handlebars": "^4.7.8",
		"lucide-react": "^0.518.0",
		"meilisearch": "^0.53.0",
		"pg": "^8.13.0",
		"puppeteer": "^24.15.0",
		"react-instantsearch": "^7.17.0",
		"resend": "^4.7.0",
		"stripe": "^17.5.0",
		"uuid": "^9.0.1"
	},
	"devDependencies": {
		"@medusajs/test-utils": "^2.13.0",
		"@mikro-orm/cli": "6.4.16",
		"@react-email/preview-server": "^4.2.5",
		"@swc/core": "^1.7.28",
		"@swc/jest": "^0.2.36",
		"@types/jest": "^29.5.13",
		"@types/node": "^20.0.0",
		"@types/react": "^18.3.2",
		"@types/react-dom": "^18.2.25",
		"@types/uuid": "^9.0.8",
		"@typescript-eslint/eslint-plugin": "^7.18.0",
		"@typescript-eslint/parser": "^7.18.0",
		"eslint": "^8.57.1",
		"eslint-config-prettier": "^9.1.0",
		"eslint-import-resolver-typescript": "^3.6.1",
		"eslint-plugin-import": "^2.29.1",
		"eslint-plugin-prettier": "^5.4.0",
		"eslint-plugin-unused-imports": "^3.0.0",
		"jest": "^29.7.0",
		"prettier": "^3.5.3",
		"prop-types": "^15.8.1",
		"react": "^18.2.0",
		"react-dom": "^18.2.0",
		"react-email": "^4.2.5",
		"ts-node": "^10.9.2",
		"typescript": "^5.6.2",
		"vite": "^5.2.11",
		"yalc": "^1.0.0-pre.53"
	},
	"engines": {
		"node": ">=20"
	}
}
```

### Node.js version

v20.19.4

### Database and its version

16.9 (installed via Homebrew)

### Operating system name and version

mac OS Sequoia 15.7.3 (24G419)

### Browser name

Google Chrome

### What happended?

After updating to Medusa 2.13.0, order totals in the admin dashboard show incorrect values. The total only
   reflects shipping costs instead of the full order amount (items + shipping + taxes).                     
                                                                                                            
  The root cause is in packages/modules/order/src/services/order-module-service.ts. The                     
  addRelationsToCalculateTotals method (around line 423-429) filters out select fields that start with      
  required relation paths. When fetching orders with specific field selections, this filtering removes      
  items.quantity from the query, causing quantity to be undefined. Since totals are calculated dynamically  
  using quantity, all item totals compute to 0.        

### Expected behavior

  Order totals should display the correct sum of item prices, taxes, and shipping - e.g., an order with a   
  €15 item + €8.95 shipping should show €23.95 total.            

### Actual behavior

                                                                                                          
  Order totals only show shipping amount (€8.95). Item totals are 0 because items.quantity is undefined due 
  to the select field filtering in addRelationsToCalculateTotals.

Additional context:                                                       
                                                                                                            
  // The problematic code in addRelationsToCalculateTotals:                                                 
  config.select = config.select.filter((field) => {                                                         
    return (                                                                                                
      !requiredRelationsForTotals.some((val) =>                                                             
        val.startsWith(field as string)  // This incorrectly filters out items.quantity                     
      ) && !totalFields.includes(field)                                                                     
    )                                                                                                       
  })                                                                                                        
                                                                                                            
  Suggested fix: Adjust the filter logic to preserve fields like items.quantity that are needed for totals  
  calculation, or ensure items.quantity is explicitly added back after filtering.                 

### Link to reproduction repo

  N/A - Bug is reproducible on any Medusa 2.13.0+ installation. See detailed root cause analysis below with    exact file locations.

### PR DESCRIPTION
**Pull request by fPolic**
**What**
- ensure correct `item` data is loaded when calculating totals

**Issue**
- adding `compensateRelationFieldsSelectionFromLoadStrategy` in the select-in path forces explicit field selection for populated relations
- In `mapRepositoryToOrderModel`, `items.*` is remapped to `items.item.*`, which drops `OrderItem` fields (quantity) because those live on `items/items.detail`, not on `items.item` (`OrderLineItem`).

---

CLOSES https://github.com/medusajs/medusa/issues/14628

### CODE REVIEW

**Comment by olivermrbl** [comment]
is this ready for review? think we should get this merged and released as soon as possible

**Comment by fPolic** [comment]
yes, ready! let me know what you think. 
alternativley we could change mappings in the `mapRepositoryToOrderModel` maybe, but this would introduce more changes IMO

**Comment by olivermrbl** [comment]
Not very familiar with the recent changes, perhaps @adrien2p or @NicolasGorga can give this a review.

File: packages/modules/order/src/utils/base-repository-find.ts [hunk 1]
```diff
@@ -5,6 +5,47 @@ import { Order, OrderClaim, OrderLineItemAdjustment } from "@models"
...
+function ensureOrderItemFieldsSelection(config: any, isRelatedEntity: boolean) {
+  const populate = config.options?.populate ?? []
+  const fields = config.options?.fields ?? []
+
+  const hasItemsItemPopulate = populate.some(
+    (p: string) =>
+      p === "items.item" ||
+      p.startsWith("items.item.") ||
+      p === "order.items.item" ||
+      p.startsWith("order.items.item.")
```
Comment (olivermrbl) [inline packages/modules/order/src/utils/base-repository-find.ts:17]: nit: could we just do `p.includes("items.item")`

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Review by olivermrbl — APPROVED** [review]
LGTM

**Review by adrien2p — COMMENTED** [review]
isnt `compensateRelationFieldsSelectionFromLoadStrategy` supposed to have done that already? normally it looks at the populate, if there is a relation for which no fields are provided it should request them all like:

```ts
 if (
        fields.some((field: string) => field.startsWith(populateRelation + "."))
      ) {
        return
      }

      // If there is no specific fields selected for the relation but the relation is populated, we select all fields
      fields.push(populateRelation + ".*")
```

cc @olivermrbl maybe there is something to investigate there but it works in all other repositories 🤔

**Comment by fPolic** [comment]
In other repositories works because the requested relation willl be in `populate` right? In the order module we do this remapping, which causes a discrepancy. If `items.quantity` is requested `items.item` is populated in `mapRepositoryToOrderModel`, the `items` relation is not added to `populate` and we won't get `items.*` added in `compensateRelationFieldsSelectionFromLoadStrategy` which would fetch `items.quantity` that we need for totals.
