### PR TITLE
fix: migrate return reasons list to new DataTable component

### LINKED ISSUE #14812: [Admin] Return Reasons list uses legacy _DataTable, missing search/sort unlike Refund Reasons
### Description

The Return Reasons settings page uses the legacy `_DataTable` component with `noHeader: true`, which hides search and lacks sorting. The Refund Reasons page uses the newer `DataTable` component with full search, sorting, and empty state support. These two very similar pages have inconsistent UX.

### Steps to Reproduce

1. Open the admin dashboard
2. Navigate to Settings > Return Reasons — no search bar, no column sorting
3. Navigate to Settings > Refund Reasons — has search bar, column sorting, and proper column headers

### Expected Behavior

Return Reasons should have the same table features as Refund Reasons: search, column sorting, column headers, and empty state messages.

### Actual Behavior

Return Reasons uses the legacy `_DataTable` with `noHeader: true`, resulting in:
- No search functionality visible
- No column sorting
- No column headers (value and label are displayed without labels)
- No empty state messages

### Location

**Return Reasons (legacy):**
- `packages/admin/dashboard/src/routes/return-reasons/return-reason-list/components/return-reason-list-table/return-reason-list-table.tsx` — uses `_DataTable` from `components/table/data-table`
- `packages/admin/dashboard/src/hooks/table/columns/use-return-reason-table-columns.tsx` — uses `createColumnHelper` from `@tanstack/react-table` (no sorting, no headers)

**Refund Reasons (current):**
- `packages/admin/dashboard/src/routes/refund-reasons/refund-reason-list/components/refund-reason-list-table/refund-reason-list-table.tsx` — uses `DataTable` from `components/data-table`
- `packages/admin/dashboard/src/hooks/table/columns/use-refund-reason-table-columns.tsx` — uses `createDataTableColumnHelper` from `@medusajs/ui` (with sorting, headers)

### Suggested Fix

Migrate Return Reasons to use the same `DataTable` component and `createDataTableColumnHelper` pattern used by Refund Reasons.

### Environment

- Medusa version: 2.13.1

### PR DESCRIPTION
**Pull request by TheSeydiCharyyev**
## What

  Migrates the Return Reasons settings page from the legacy `_DataTable` component to the newer `DataTable` component, matching the pattern already used by the Refund Reasons page.

  ## Why

  The Return Reasons page uses the legacy `_DataTable` with `noHeader: true`, which hides search, column sorting, and column headers. The Refund Reasons page already uses the modern
  `DataTable` component with full functionality. This inconsistency was reported in #14812.

  ## How

  - **`use-return-reason-table-columns.tsx`** — Replaced `createColumnHelper` from `@tanstack/react-table` with `createDataTableColumnHelper` from `@medusajs/ui`. Added column headers,
  sorting, and `DescriptionCell` for the description column.
  - **`return-reason-list-table.tsx`** — Replaced `_DataTable` + manual header with the new `DataTable` component. Added built-in search, heading, empty states, and inline action menu
  (edit/delete) using `columnHelper.action()`.
  - **`return-reasons.tsx`** — Added `useDeleteReturnReasonLazy` hook (lazy variant where `id` is passed to `mutationFn`) to support the new inline delete action pattern.

  ## Testing

  1. Navigate to Settings > Return Reasons
  2. Verify search bar is visible and functional
  3. Verify column headers (Label, Value, Description) are displayed
  4. Verify column sorting works on all columns
  5. Verify edit and delete actions work via row action menu
  6. Compare UX with Settings > Refund Reasons — should be consistent

  Fixes #14812

---

> [!NOTE]
> **Low Risk**
> Low risk UI refactor that swaps table components and rewires row actions; main risk is regressions in list interactions (search/sort/navigation/delete) due to the new DataTable API and mutation wiring.
> 
> **Overview**
> Migrates the Return Reasons settings list from the legacy `_DataTable` to the newer `DataTable`, restoring built-in header UI including **search, empty states, and column sorting**.
> 
> Updates return-reason columns to use `createDataTableColumnHelper` with translated headers and a dedicated `DescriptionCell`, and moves edit/delete into an inline row action column (with prompt + toasts and explicit navigation).
> 
> Adds `useDeleteReturnReasonLazy` (id passed at call time) and removes the old `useDeleteReturnReasonAction` helper, while keeping query invalidation behavior for list/detail refresh after deletes.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit fe789c0b1a6edbd70945ad2246d508c37a9feaf8. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by NicolasGorga** [comment]
@claude review this

**Comment by TheSeydiCharyyev** [comment]
Addressed the review feedback:                                                                                                                                                            
                                                                                                                                                                                            
  1. Removed the orphaned `useDeleteReturnReasonAction` hook file — no longer used after migrating to inline delete logic with `useDeleteReturnReasonLazy`                                  
  2. Fixed missing `{ label }` interpolation in the delete success toast (`returnReasons.delete.successToast`)

**Comment by NicolasGorga** [comment]
@medusajs-bot review

**Review by NicolasGorga — CHANGES_REQUESTED** [review]
@TheSeydiCharyyev could you include a video showing the table? Also, the previous had pagination enabled, while this doesn't could you add pagination handling?

**Comment by TheSeydiCharyyev** [comment]
@NicolasGorga video attached showing the table with search, sorting, and pagination.    

https://github.com/user-attachments/assets/740ec416-a8ba-4b13-b622-a43fd0ee8754

Regarding pagination — it's already enabled. The new `DataTable` sets `enablePagination` to `true` by default, and `useReturnReasonTableQuery` handles `offset`/`limit` — same pattern as Refund Reasons. The footer only renders when there are enough records; with 20+ it shows up as in the video.

**Review by NicolasGorga — APPROVED** [review]
lgtm, thanks for the contribution!

**Comment by NicolasGorga** [comment]
@shahednasser would be more of a feature than a fix no?

File: packages/admin/dashboard/src/hooks/api/return-reasons.tsx [hunk 1]
```diff
@@ -130,3 +130,30 @@ export const useDeleteReturnReason = (
     ...options,
   })
 }
+
+export const useDeleteReturnReasonLazy = (
```
Comment (shahednasser) [inline packages/admin/dashboard/src/hooks/api/return-reasons.tsx]: I see useDeleteReturnReason isn't used anywhere anymore. Delete it and rename this one to be `useDeleteReturnReason`

**Review by shahednasser — CHANGES_REQUESTED** [review]
Just a small change. Also you I think in this case whether it's a fix or feature isn't a big difference.

**Comment by TheSeydiCharyyev** [comment]
@shahednasser done — removed the unused old `useDeleteReturnReason` hook and renamed `useDeleteReturnReasonLazy` → `useDeleteReturnReason`. The table now uses the single consolidated hook.

**Review by shahednasser — APPROVED** [review]
LGTM thanks!
