### PR TITLE
fix(dashboard): Load product variant edit page and fix product detail query key

### LINKED ISSUE #10025: [Bug]: Edit Variant page - An unexpected error occurred while rendering this page - recent update
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "predeploy": "medusa db:migrate",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

20

### Database and its version

16

### Operating system name and version

ubuntu 22

### Browser name

safari and chrome

### What happended?

After this recent update the variant edit page gives the following error:

An error occurred
An unexpected error occurred while rendering this page.

when we use the old version it starts to work

### Expected behavior

Popup windows to be opened for dining Upc quantity etc.

### Actual behavior

An error occurred
An unexpected error occurred while rendering this page.

### Link to reproduction repo

https://github.com/medusajs/medusa-starter-default.git

### PR DESCRIPTION
**Pull request by kasperkristensen**
**What**
- Fixes Edit Variant form so it properly loads the product variant
- Fixes the query key for product details to prevent the cache from being shared between queries for the same ID but with different params.

Resolves CMRC-685

### CODE REVIEW

**Review by fPolic — COMMENTED** [review]
TODO: this breaks editing variant from the product page (opened modal is just empty)

File: packages/admin/dashboard/src/hooks/api/products.tsx [hunk 1]
```diff
@@ -87,9 +87,14 @@ export const useDeleteProductOption = (
 export const useProductVariant = (
```
Comment (fPolic) [inline packages/admin/dashboard/src/hooks/api/products.tsx:87]: We need to add the same fix here you did for for product (include the `query` in query key).
If you open edit variant from product and then go to variant page it will break since pulling the variant from the same cache key.

**Review by fPolic — COMMENTED** [review]
Edits work as expected, we have one more thing to add:

**Review by olivermrbl — APPROVED** [review]
Seems to be working fine, LGTM. @fPolic can you please add a final review?

**Review by fPolic — APPROVED** [review]
LGTM
