### PR TITLE
fix(payment): Double idempotent capture called with auto capture beha…

### LINKED ISSUE #13301: [Bug]: core stripe payment integration - double /capture api
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start -p 9777",
    "dev": "medusa develop -p 9777",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "full-cost-reconcile": "node -r dotenv/config -r ts-node/register src/scripts/full-cost-reconciliation.ts",
    "per-message-costs": "node -r dotenv/config -r ts-node/register src/scripts/per-message-cost-tracker.ts",
    "monitor-db-pool": "node -r dotenv/config -r ts-node/register src/scripts/monitor-db-pool.ts",
    "backfill-tiers": "medusa exec ./src/scripts/backfill-customer-tiers-merged.ts"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "latest",
    "@medusajs/cli": "latest",
    "@medusajs/framework": "latest",
    "@medusajs/medusa": "latest",
    "@mikro-orm/core": "6.4.3",
    "@mikro-orm/knex": "6.4.3",
    "@mikro-orm/migrations": "6.4.3",
    "@mikro-orm/postgresql": "6.4.3",
    "@sendgrid/eventwebhook": "^8.0.0",
    "awilix": "^8.0.1",
    "multer": "^1.4.5-lts.1",
    "pg": "^8.13.0",
    "twilio": "^5.3.3"
  },
  "devDependencies": {
    "@medusajs/test-utils": "latest",
    "@mikro-orm/cli": "6.4.3",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/multer": "^1.4.12",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11",
    "yalc": "^1.0.0-pre.53"
  },
  "engines": {
    "node": ">=20"
  },
  "packageManager": "yarn@3.2.3+sha512.f26f951f67de0c6a33ee381e5ff364709c87e70eb5e65c694e4facde3512f1fa80b8679e6ba31ce7d340fbb46f08dd683af9457e240f25a204be7427940d767e"
}
```

### Node.js version

v20.18.1

### Database and its version

PostgreSQL 15.6

### Operating system name and version

Ubuntu 25.04

### Browser name

Brave

### What happended?

The stripe endpoint /capture is called twice on a ``processPaymentWorkflow`` event whether manual or automatic capture from medusa-config.ts. I even tested with two different version frontend package versions and see the results below:

Default versions used by medusajs packages (core medusa stripe integration and nextjs-starter) 

```log
backend medusajs: 
@medusajs/medusa@2.9.0 invalid: "latest" from the root project
  └─┬ @medusajs/payment-stripe@2.9.0
    └── stripe@15.12.0
```
```log
frontend nextjs:
├── @stripe/react-stripe-js@1.16.5
├── @stripe/stripe-js@1.54.2
```
Here find the following: Multiple calls to stripe /capture api endpoint 

1. top manual capture
``"capture_method": "manual"``
2. bottom automatic 
``"capture_method": "automatic"``

Image

Different package version frontend
```log
backend medusajs: 
@medusajs/medusa@2.9.0 invalid: "latest" from the root project
  └─┬ @medusajs/payment-stripe@2.9.0
    └── stripe@15.12.0
```
```log
frontend nextjs:
├── @stripe/react-stripe-js@3.9.2
├── @stripe/stripe-js@7.9.0
```
Here find the following: mutiple calls to strpipe /capture api endpoint on manual, 1 /capture and 1 /cancel on auto

1. top manual capture
``"capture_method": "manual"``
2. bottom automatic 
``"capture_method": "automatic"``

Image

Payment is successfully captured in both scenarios with both package versions. However at times there can occur a race condition between the capture events and the .confirmPayment on the nextjs frontend leading to a refund after an order is successfully processed and fulfilled in the case of digital products. 

### Expected behavior

1. payment intent created
2. .confirmPayment - if ``capture: true`` this is where payment is collected as ``"capture_method": "automatic"`` is passed due to the config below in medusa-config.ts
```ts
{
      resolve: "@medusajs/medusa/payment",
      options: {
        providers: [
          {
            resolve: "@medusajs/medusa/payment-stripe",
            id: "stripe",
            options: {
              apiKey: process.env.STRIPE_API_KEY,
              webhookSecret: process.env.STRIPE_WEBHOOK,
              automatic_payment_methods: true,
              capture: true,
            },
          },
        ],
      },
    },
```
3. order created after success response from .confirmPayment
4. There would be no need for the /capture api calls if ``capture: true``

### Actual behavior

1. payment intent created
2. .confirmPayment - payment is captured  - race conditions occur 1/1000
3. order created after success response from .confirmPayment  
4. ``processPaymentWorkflow`` - /capture api call
5. ``processPaymentWorkflow`` - /capture api call (from webhook response) 

### Link to reproduction repo

https://github.com/medusajs/medusa-starter-default/

### PR DESCRIPTION
**Pull request by adrien2p**
FIXES https://github.com/medusajs/medusa/issues/13301

**What**
When a payment provider is configured with `auto_capture` our payment flows are still calling the external provider to capture the payment, even though this flow is idempotent and we gracefully handle it, it seems reasonable to not even call the third party at that point.

---

> [!NOTE]
> Skips provider capture when authorization returns captured, adds `is_captured` flag to captures, and updates service logic and tests accordingly.
> 
> - **Payment Service**:
>   - Treat `authorizePayment` returning `captured` as authorized + auto-captured; pass `is_captured` to `capturePayment`.
>   - Update `capturePayment` to accept `is_captured`, infer auto-capture from `captured_at`, and avoid calling provider when already captured.
>   - Refactor `capturePaymentFromProvider_` to accept `{ isFullyCaptured, isCaptured }`; skip provider call if `isCaptured`, only set `captured_at` when fully captured.
> - **Types**:
>   - Add `is_captured?: boolean` to `CreateCaptureDTO` in `@medusajs/types`.
> - **Tests**:
>   - Add integration tests to validate auto-capture behavior and ensure provider `capturePayment` is not called on auto-captured payments.
> - **Changeset**:
>   - Patch releases for `@medusajs/payment` and `@medusajs/types`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 9f049d797e84cc1fa9e9e0e776cd24874011da81. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/modules/payment/src/services/payment-module.ts [hunk 1]
```diff
@@ -763,27 +773,44 @@ export default class PaymentModuleService
   protected async capturePaymentFromProvider_(
     payment: InferEntityType<typeof Payment>,
     capture: InferEntityType<typeof Capture> | undefined,
-    isFullyCaptured: boolean,
+    options: {
+      isFullyCaptured?: boolean
+      auto_captured?: boolean
```
Comment (olivermrbl) [inline packages/modules/payment/src/services/payment-module.ts]: nit: should be camelCased

**Comment by adrien2p** [comment]
cc @olivermrbl if you d like to have a quick glance over it

File: packages/modules/payment/src/services/payment-module.ts [hunk 2]
```diff
@@ -665,8 +670,13 @@ export default class PaymentModuleService
       sharedContext
     )
 
+    if (!auto_captured) {
+      const isAutoCaptured = !!payment?.captured_at
+      auto_captured = isAutoCaptured
+    }
```
Comment (olivermrbl) [inline packages/modules/payment/src/services/payment-module.ts]: thought: I guess this isn't really specific to auto capture, but more a general guard to ensure we don't attempt to capture an already-captured payment. With that in mind, maybe we should change the flag to `isCaptured`.

And then we should be able to avoid calling `capturePaymentFromProvider_` if `isCaptured && isFullyCaptured`.

Update: maybe we don't need the flag at all, but can just use `payment.captured_at`?

**Review by olivermrbl — COMMENTED** [review]
LGTM

File: packages/modules/payment/src/services/payment-module.ts (hunk 2 above)
Comment (adrien2p) [reply packages/modules/payment/src/services/payment-module.ts]: we still call `capturePaymentFromProvider_` to update the capturedAt column if not set but for some reason it is captured. more of a safeguard than anything else

File: packages/core/types/src/payment/mutations.ts [hunk 3]
```diff
@@ -147,6 +151,11 @@ export interface CreateCaptureDTO {
    * a user's ID.
    */
   captured_by?: string
+
+  /**
+   * Whether the capture was automatically captured.
+   */
+  isCaptured?: boolean
```
Comment (olivermrbl) [inline packages/core/types/src/payment/mutations.ts]: nit: this shouldn't be camelCased, only the local variable declaration in the function and the property in the options argument to `capturePaymentFromProvider_` 😄

File: packages/modules/payment/src/services/payment-module.ts [hunk 4]
```diff
@@ -763,27 +773,44 @@ export default class PaymentModuleService
...
+      )
+    } else if (options.isFullyCaptured && !payment.captured_at) {
+      /**
+       * In the case of auto capture, we need to update the payment to set the captured_at date
+       * only if fully captured.
+       */
+      await this.paymentService_.update(
+        {
+          id: payment.id,
+          captured_at: options.isFullyCaptured ? new Date() : undefined,
```
Comment (olivermrbl) [inline packages/modules/payment/src/services/payment-module.ts]: nit: we are already checking for a full capture in the else-if
```suggestion
          captured_at: new Date(),
```

File: packages/core/types/src/payment/mutations.ts (hunk 3 above)
Comment (adrien2p) [reply packages/core/types/src/payment/mutations.ts]: ahah my bad :D

**Review by olivermrbl — APPROVED** [review]
