### PR TITLE
fix(dashboard): use order version 1 for the initial node of activity timeline

### LINKED ISSUE #13705: [Bug]: Order Placed total changes with order edits
### Package.json file

```JSON
{
  "packageManager": "yarn@4.2.2",
  "name": "wildkind-medusa",
  "version": "0.0.1",
  "description": "Wildkind ticketing platform",
  "author": "Wildkind (https://wildkind.co.uk)",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build && yarn lint && yarn test:unit && yarn tsc --noEmit && yarn tsc-alias",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa build && medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test": "yarn test:unit && yarn test:integration:modules && yarn test:integration:http",
    "lint": "eslint .",
    "sentry:sourcemaps": "sentry-cli sourcemaps inject --org wildkind --project medusa .medusa && sentry-cli sourcemaps upload --org wildkind --project medusa .medusa"
  },
  "dependencies": {
    "@getbrevo/brevo": "^2.2.0",
    "@medusajs/admin-sdk": "2.10.3",
    "@medusajs/cli": "2.10.3",
    "@medusajs/draft-order": "2.10.3",
    "@medusajs/framework": "2.10.3",
    "@medusajs/medusa": "2.10.3",
    "@mikro-orm/core": "6.4.3",
    "@mikro-orm/knex": "6.4.3",
    "@mikro-orm/migrations": "6.4.3",
    "@mikro-orm/postgresql": "6.4.3",
    "@opentelemetry/api": "^1.9.0",
    "@opentelemetry/exporter-trace-otlp-grpc": "^0.200.0",
    "@opentelemetry/instrumentation-pg": "0.52.0",
    "@opentelemetry/resources": "2.0.1",
    "@opentelemetry/sdk-node": "0.200.0",
    "@opentelemetry/sdk-trace-node": "2.0.1",
    "@sentry/cli": "^2.44.0",
    "@sentry/node": "^9.15.0",
    "@sentry/opentelemetry-node": "^7.114.0",
    "@woocommerce/woocommerce-rest-api": "^1.0.1",
    "awilix": "^8.0.1",
    "aws-sdk": "^2.1692.0",
    "body-parser": "^1.19.0",
    "cors": "^2.8.5",
    "cross-env": "^7.0.3",
    "dotenv": "16.4.7",
    "express": "^4.17.2",
    "firebase-admin": "^13.0.2",
    "js-base64": "^3.7.7",
    "lodash": "^4.17.21",
    "mixpanel": "^0.18.1",
    "moment": "^2.30.1",
    "p-map": "^4.0.0",
    "pg": "^8.13.0",
    "prism-react-renderer": "^2.0.4",
    "react-select": "^5.8.3"
  },
  "devDependencies": {
    "@babel/cli": "^7.14.3",
    "@babel/core": "^7.14.3",
    "@babel/preset-typescript": "^7.21.4",
    "@eslint/js": "^9.14.0",
    "@medusajs/test-utils": "^2.10.3",
    "@mikro-orm/cli": "6.4.3",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.37",
    "@testing-library/dom": "^10.4.0",
    "@testing-library/react": "^16.0.1",
    "@types/eslint__js": "^8.42.3",
    "@types/express": "^4.17.13",
    "@types/jest": "^29.5.14",
    "@types/lodash": "^4",
    "@types/node": "^17.0.8",
    "@types/react": "^18.3.12",
    "@types/react-dom": "^18.3.1",
    "@types/woocommerce__woocommerce-rest-api": "^1",
    "babel-preset-medusa-package": "^1.1.19",
    "eslint": "^9.16.0",
    "jest": "^29.7.0",
    "rimraf": "^3.0.2",
    "ts-jest": "^27.0.7",
    "ts-loader": "^9.2.6",
    "ts-node": "^10.9.2",
    "tsc-alias": "^1.8.6",
    "typescript": "^5.9.3",
    "typescript-eslint": "^8.18.0"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v21.6.2

### Database and its version

N/A

### Operating system name and version

N/A

### Browser name

_No response_

### What happended?

If a customer places an order, then create an order edit to add an additional item at a later point, the total shown at "Order Placed" in the order timeline changes to the new order total, as shown in the screenshot below.  This behaviour can lead to confusion

Image

### Expected behavior

The order placed value in order activity should remain as the original order total, when the order was placed.

### Actual behavior

The original order placed value is getting updated by the order edit

### Link to reproduction repo

N/A

### PR DESCRIPTION
**Pull request by NicolasGorga**
## Summary

**What** — What changes are introduced in this PR?

Use the order's first version to construct the initial node of the order activity timeline in the admin panel.

**Why** — Why are these changes relevant or necessary?  

Without this if the order has any type of order_change_action confirmed that updates its `total` value, then the initial value when the order was placed incorrectly shows the latest `total`, which is incorrect in the context of the order's placement.

**How** — How have these changes been implemented?

Retrieve the order's first version to construct the initial node of the activity timeline.

**Testing** — How have these changes been tested, or how can the reviewer test the feature?

The order with a confirmed order edit to add an item shows the correct initial `total` value for the first node of the activity timeline, which is less than the latest version `total`.

---

## Examples

Provide examples or code snippets that demonstrate how this feature works, or how it can be used in practice.  
This helps with documentation and ensures maintainers can quickly understand and verify the change.

```ts
// Example usage
```

---

## Checklist

Please ensure the following before requesting a review:

- [x] I have added a **changeset** for this PR
    - Every non-breaking change should be marked as a **patch**
    - To add a changeset, run `yarn changeset` and follow the prompts
- [ ] The changes are covered by relevant **tests**
- [x] I have verified the code works as intended locally
- [x] I have linked the related issue(s) if applicable

---

## Additional Context

Add any additional context, related issues, or references that might help the reviewer understand this PR.

fixes #13705 
closes SUP-2495, CORE-1189

### CODE REVIEW

**Review by fPolic — APPROVED** [review]
LGTM

File: packages/admin/dashboard/src/routes/orders/order-detail/components/order-activity-section/order-timeline.tsx [hunk 1]
```diff
@@ -123,6 +124,8 @@ type Activity = {
 const useActivityItems = (order: AdminOrder): Activity[] => {
   const { t } = useTranslation()
 
+  const { order: firstOrderVersion = {} } = useOrder(order.id, { version: 1, fields: "created_at,total,currency_code" })
```
Comment (fPolic) [inline packages/admin/dashboard/src/routes/orders/order-detail/components/order-activity-section/order-timeline.tsx]: suggestion: we can check if `order` from props is v1 and can skip the fetch in that case

Comment (NicolasGorga) [reply packages/admin/dashboard/src/routes/orders/order-detail/components/order-activity-section/order-timeline.tsx]: Nice, will do!

File: packages/admin/dashboard/src/routes/orders/order-detail/components/order-activity-section/order-timeline.tsx [hunk 2]
```diff
@@ -123,6 +124,15 @@ type Activity = {
 const useActivityItems = (order: AdminOrder): Activity[] => {
   const { t } = useTranslation()
 
+  let firstOrderVersion = order
+  if (firstOrderVersion.version !== 1) {
+    const { order: initialOrder = {} } = useOrder(firstOrderVersion.id, {
```
Comment (fPolic) [inline packages/admin/dashboard/src/routes/orders/order-detail/components/order-activity-section/order-timeline.tsx]: we shouldn't render a hook conditionally, you can use `enabled` flag:

```
const { order: initialOrder =  order} = useOrder(
    firstOrderVersion.id, 
    { version: 1, fileds: "..." }, 
    {enabled: firstOrderVersion.version !== 1}
)
```

Comment (NicolasGorga) [reply packages/admin/dashboard/src/routes/orders/order-detail/components/order-activity-section/order-timeline.tsx]: Oops changed
