### PR TITLE
fix(medusa-oas-cli): fix download url for public OAS

### LINKED ISSUE #8762: Fix URL in getPublicOas Function to Correct API Spec Download Path @medusajs/medusa-oas-cli
## Bug report

I encountered an issue after installing a fresh oas package using the following command:

```bash
yarn add --dev @medusajs/medusa-oas-cli@preview
``` 

Upon running generate command, I received the following error:

```bash
ResolverError: Error downloading https://docs.medusajs.com/v2/api/download/admin 
HTTP ERROR 404
    at /Users/vholik/Desktop/medusa-2-0/node_modules/@readme/json-schema-ref-parser/lib/resolvers/http.js:101:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERESOLVER',
  source: 'https://docs.medusajs.com/v2/api/download/admin',
  path: null,
  toJSON: [Function: toJSON],
  [Symbol(nodejs.util.inspect.custom)]: [Function: inspect]
}
```

### Describe the bug

I was able to resolve the issue by modifying the `getPublicOas` URL in the package code.

```diff
async function getPublicOas(apiType) {
-    const url = `https://docs.medusajs.com/v2/api/download/${apiType}`;
+    const url = `https://docs.medusajs.com/api/download/${apiType}`;
    return await openapi_parser_1.default.parse(url);
}
```

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

### PR DESCRIPTION
**Pull request by shahednasser**
Closes #8762

### CODE REVIEW

File: packages/cli/oas/medusa-oas-cli/src/command-oas.ts [hunk 1]
```diff
@@ -161,7 +161,7 @@ async function getOASFromCodebase(
 async function getPublicOas(
   apiType: ApiType,
 ) {
-  const url = `https://docs.medusajs.com/v2/api/download/${apiType}`
+  const url = `https://docs.medusajs.com/v2/api/api/download/${apiType}`
```
Comment (olivermrbl) [inline packages/cli/oas/medusa-oas-cli/src/command-oas.ts:164]: question: why is it `/api/api`?

Comment (shahednasser) [reply packages/cli/oas/medusa-oas-cli/src/command-oas.ts:164]: Due to how the API reference is built, we have to use a base path `/v2/api` to have routes like `/v2/api/store` and `/v2/api/admin`, which means actual APIs in the project are under `/v2/api/api`.

This setup wasn't in the v1 API reference because it was the main proxy project (i.e. no other projects redirecting to it based on the page's path). For the v2 API reference, using just a `/v2` base path causes redirect and 404 errors when trying to fetch its static files (CSS, js, etc...) through the proxy (as it tries to fetch these files from other doc projects). So, it has to be under a `/v2/api` base path.
