### PR TITLE
fix(dashboard): bust variant inventory cache on inventory update

### LINKED ISSUE #11686: [Bug]:The product inventory on the admin dashboard is not updating immediately after changes are made.
### Package.json file

```JSON
{
  "name": "medusa-starter-default",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@medusajs/admin-sdk": "2.1.3",
    "@medusajs/cli": "2.1.3",
    "@medusajs/framework": "2.1.3",
    "@medusajs/medusa": "2.1.3",
    "@mikro-orm/core": "5.9.7",
    "@mikro-orm/knex": "5.9.7",
    "@mikro-orm/migrations": "5.9.7",
    "@mikro-orm/postgresql": "5.9.7",
    "awilix": "^8.0.1",
    "pg": "^8.13.0"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.1.3",
    "@mikro-orm/cli": "5.9.7",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v20.16.0

### Database and its version

PostgreSQL 14

### Operating system name and version

macOS Sequoia 15.3.1

### Browser name

Google Chrome , Brave , Safari

### What happended?

I had to change the quantity of products in the inventory. After Toast's success, I tried to go back to the product detail page. The quantity of products in the inventory still shows the same until the refresh page
https://github.com/user-attachments/assets/2f53f5de-2272-4e45-b15b-1312443c9180

### Expected behavior

When back to the product detail page. The quantity of products shows new value.

### Actual behavior

The quantity of products in the inventory still shows the same until the refresh page

### Link to reproduction repo

-

### PR DESCRIPTION
**Pull request by riqwan**
what:

- busts variant cache on inventory level update

FIXES https://github.com/medusajs/medusa/issues/11686

### CODE REVIEW

**Review by kasperkristensen — APPROVED** [review]

**Review by fPolic — APPROVED** [review]

File: packages/admin/dashboard/src/hooks/api/inventory.tsx [hunk 1]
```diff
@@ -205,6 +205,9 @@ export const useUpdateInventoryLevel = (
       queryClient.invalidateQueries({
         queryKey: inventoryItemLevelsQueryKeys.detail(inventoryItemId),
       })
+      queryClient.invalidateQueries({
```
Comment (fPolic) [inline packages/admin/dashboard/src/hooks/api/inventory.tsx:208]: q: should we invalidate the product details as well for places where we fetch inventory with the product endpoint

Comment (riqwan) [reply packages/admin/dashboard/src/hooks/api/inventory.tsx:208]: where would that be?

**Review by carlos-r-l-rodrigues — APPROVED** [review]

File: packages/admin/dashboard/src/hooks/api/inventory.tsx (hunk 1 above)
Comment (fPolic) [reply packages/admin/dashboard/src/hooks/api/inventory.tsx:208]: sorry nvm, tought we fetch it like that on prod details
