### PR TITLE
fix(medusa): Support q search and order in list regions

### LINKED ISSUE #6174: bug(medusa): Missing list params on `/admin/regions`
### Describe the bug

The `GET /admin/regions` endpoint is currently missing two key params: `q` and `order`. This makes it difficult to quickly find a specific region, or to order the returned data in a order that is relevant to the user. 

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

### PR DESCRIPTION
**Pull request by olivermrbl**
Closes #6174

### CODE REVIEW

File: packages/medusa/src/services/region.ts [hunk 1]
```diff
@@ -533,7 +533,28 @@ class RegionService extends TransactionBaseService {
...
+      q = selector.q
+      delete selector.q
+    }
+
     const query = buildQuery(selector, config)
+
+    if (q) {
+      const where = query.where as FindOptionsWhere<Region>
+
+      delete where.name
```
Comment (olivermrbl) [inline packages/medusa/src/services/region.ts:548]: @kasperkristensen, only included the name for now. Let me know if this is sufficient.

Comment (kasperkristensen) [reply packages/medusa/src/services/region.ts:548]: I think that is fine, the only other option I think would make sense was to allow search by country, like how we have search product variants by product title: https://github.com/medusajs/medusa/blob/f29948a6a8189d9662ad28ba6d0a41c5bf2d4df8/packages/medusa/src/services/product-variant.ts#L923-L949

Would be cool to be able to search "denmark" and then "Europe" pops up, but I am good with leaving that for a future iteration 😄

**Review by kasperkristensen — APPROVED** [review]
LGTM!
