### PR TITLE
fix(medusa): Support q search in currencies

### LINKED ISSUE #6175: bug(currencies): Missing `q` param on `GET /admin/currencies`
### Describe the bug

It is currently not possible to use free text search on the currencies endpoint, making it hard to quickly find a currency in the Admin dashboard.

### System information

Medusa version (including plugins):
Node.js version:
Database:
Operating system:
Browser (if relevant):

### Expected behavior

A clear and concise description of what you expected to happen

### Screenshots

If applicable, add screenshots to help explain your problem

### Code snippets

If applicable, add code samples to help explain your problem

### Additional context

Add any other context about the problem here

### PR DESCRIPTION
**Pull request by olivermrbl**
Closes #6175

### CODE REVIEW

File: integration-tests/api/__tests__/admin/currency.js [hunk 1]
```diff
@@ -5,6 +5,7 @@ const startServerWithEnvironment =
 const { useApi } = require("../../../environment-helpers/use-api")
 const { useDb, initDb } = require("../../../environment-helpers/use-db")
 const adminSeeder = require("../../../helpers/admin-seeder")
+const e = require("express")
```
Comment (carlos-r-l-rodrigues) [inline integration-tests/api/__tests__/admin/currency.js]: rm

**Review by carlos-r-l-rodrigues — APPROVED** [review]
LGTM

File: integration-tests/api/__tests__/admin/currency.js (hunk 1 above)
Comment (olivermrbl) [reply integration-tests/api/__tests__/admin/currency.js]: How did that sneak there :D

Comment (carlos-r-l-rodrigues) [reply integration-tests/api/__tests__/admin/currency.js]: vscode autoimport 🤣

File: packages/medusa/src/api/routes/admin/currencies/list-currencies.ts [hunk 2]
```diff
@@ -21,6 +21,7 @@ import { FeatureFlagDecorators } from "../../../../utils/feature-flag-decorators
  *       type: boolean
  *       x-featureFlag: "tax_inclusive_pricing"
  *   - (query) order {string} A field to sort order the retrieved currencies by.
+ *   - (query) q {string} term used to search currencies' name and code.
```
Comment (kasperkristensen) [inline packages/medusa/src/api/routes/admin/currencies/list-currencies.ts]: nit: 
```suggestion
 *   - (query) q {string} Term used to search currencies' name and code.
```
Otherwise I think the docs entry will look strange :D

**Review by kasperkristensen — APPROVED** [review]
LGTM, added a small nit but otherwise good to go

**Review by adrien2p — APPROVED** [review]
LGTM 🔥
