### PR TITLE
fix(medusa): Support `fields` param in list-variants

### LINKED ISSUE #5045: API Ref(store): Issue in Get Product Variants
### Preliminary Checks

- [X] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

[Get product variants store api endpoint](https://docs.medusajs.com/api/store#product-variants_getvariants) documentation says that fields can be used as query parameter to filter **fields** included in returned product variants

image

but it throws an error

image

image

### How can this issue be resolved?

_No response_

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

### PR DESCRIPTION
**Pull request by olivermrbl**
Closes #5045

### CODE REVIEW

**Comment by olivermrbl** [comment]
@adrien2p, do you have time to look at this one? Should not take much time :)

File: integration-tests/api/__tests__/store/product-variants.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ describe("/store/variants", () => {
   beforeAll(async () => {
     const cwd = path.resolve(path.join(__dirname, "..", ".."))
     dbConnection = await initDb({ cwd })
-    medusaProcess = await setupServer({ cwd })
+    medusaProcess = await setupServer({ cwd, verbose: true })
```
Comment (adrien2p) [inline integration-tests/api/__tests__/store/product-variants.js]: Todo: rm verbose

File: packages/medusa/src/api/routes/store/variants/list-variants.ts [hunk 2]
```diff
@@ -132,17 +130,11 @@ export default async (req, res) => {
...
-    expandFields = expand.split(",")
-  }
-
   const customer_id = req.user?.customer_id
 
   const listConfig = {
-    relations: expandFields.length
-      ? expandFields
-      : defaultStoreVariantRelations,
+    select: req.listConfig.select,
```
Comment (adrien2p) [inline packages/medusa/src/api/routes/store/variants/list-variants.ts]: Question: is the middleware applied for the end point?

Comment (adrien2p) [inline packages/medusa/src/api/routes/store/variants/list-variants.ts]: Suggestion : req.listConfig already include all of that, we probably can remove the const listConfig entirely

File: packages/medusa/src/api/routes/store/variants/list-variants.ts [hunk 3]
```diff
@@ -152,6 +144,7 @@ export default async (req, res) => {
     "limit",
     "offset",
     "expand",
+    "fields",
```
Comment (adrien2p) [inline packages/medusa/src/api/routes/store/variants/list-variants.ts]: Suggestion : depending on the previous one, should we use req.filterableFields?

**Review by adrien2p — CHANGES_REQUESTED** [review]

File: packages/medusa/src/api/routes/store/variants/list-variants.ts (hunk 3 above)
Comment (olivermrbl) [reply packages/medusa/src/api/routes/store/variants/list-variants.ts]: The `req.filterableFields` contains a mix of filterable fields for the ProductVariantService.list and price selection, so that's not possible without doing additional modifications.

Comment (adrien2p) [reply packages/medusa/src/api/routes/store/variants/list-variants.ts]: Something like we do usually :

const { something, ...filterableFields } = req.filterableFields 

Wdyt?

Comment (olivermrbl) [reply packages/medusa/src/api/routes/store/variants/list-variants.ts]: Shuffled it around 👍 

It doesn't change the fact that `req.filterableFields` are not behaving 100% correctly in this case, which is what I was hinting. That said, I do like this better

**Review by adrien2p — APPROVED** [review]
LGTM
