### PR TITLE
fix(utils,core-flows): fix import erasing tags, categories and others

### LINKED ISSUE #13397: [Bug]: Loss of data in product imports
### Package.json file

```JSON
{
  "name": "backend",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "private": true,
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "build:admin": "medusa build --admin-only",
    "seed": "medusa exec ./src/scripts/seed.ts",
    "start": "medusa start",
    "predeploy": "medusa db:migrate",
    "dev": "medusa develop",
    "check-types": "tsc --noEmit",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@meduline/medusa-plugin-variant-images": "^1.1.4",
    "@medusajs/admin-sdk": "2.10.1",
    "@medusajs/cli": "2.10.1",
    "@medusajs/framework": "2.10.1",
    "@medusajs/icons": "^2.10.1",
    "@medusajs/medusa": "2.10.1",
    "@medusajs/ui": "^4.0.21",
    "@mikro-orm/core": "6.4.3",
    "@mikro-orm/knex": "6.4.3",
    "@mikro-orm/migrations": "6.4.3",
    "@mikro-orm/postgresql": "6.4.3",
    "@react-email/components": "^0.5.1",
    "algoliasearch": "^5.36.0",
    "awilix": "^8.0.1",
    "pg": "^8.16.3",
    "posthog-node": "^5.8.1",
    "react-router-dom": "^7.8.2",
    "resend": "^6.0.2"
  },
  "devDependencies": {
    "@medusajs/test-utils": "2.10.1",
    "@mikro-orm/cli": "6.4.3",
    "@swc/core": "1.13.5",
    "@swc/jest": "^0.2.39",
    "@types/jest": "^30.0.0",
    "@types/node": "^24.3.0",
    "@types/react": "^19.1.12",
    "@types/react-dom": "^19.1.9",
    "jest": "^30.1.1",
    "prop-types": "^15.8.1",
    "react": "^19.1.1",
    "react-dom": "^19.1.1",
    "react-email": "4.2.8",
    "ts-node": "^10.9.2",
    "turbo": "^2.5.6",
    "typescript": "^5.9.2",
    "vite": "^7.1.3",
    "yalc": "^1.0.0-pre.53"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v22.18.0

### Database and its version

PostgreSQL 17

### Operating system name and version

MacOS 15.6.1 

### Browser name

Chrome

### What happended?

There are some important issues I think with the Import System. 

How I use exports and imports overall, is I had imported lots of products from shopify. After importing I decided to setup categories and then figured that I have to put USD price separately from CAD so I exported all again and then imported with new USD columns. I didn't find easier way to set all USD pricing for products. I could do for Variants but not all products & variants together. Its much easier way to export and import stuff. x

Product prices were loaded fine but here is what went wrong.

### Expected behavior

Categories should have not been reset. 
Products should retain the tags data, it should not be reset on import.
Optionally if there are plugin which requires some data, it should be allowed to be set by import. (It might not be best idea if the plugin requires workflow or something but something to think about)

### Actual behavior

1. All categories were emptied out. I have to select category for each now.
2. I have a custom plugin for multiple-variant-images, and it had the metadata column exported but when importing it was giving me error while importing. I just had to remove it, data are still persisted in metadata tho. So not the biggest issue.
3. I had tags already setup for products which also got reset.

### Link to reproduction repo

I can create if needed.

### PR DESCRIPTION
**Pull request by willbouch**
## Summary

**What** — What changes are introduced in this PR?

Details in [issue](https://github.com/medusajs/medusa/issues/13397). TLDR, this PR fixes removing some product options when we import from CSV

**Why** — Why are these changes relevant or necessary?  

Annoying for the merchant when they export their products, make modifications on the CSV directly and try to reimport their products.

**Testing** — How have these changes been tested, or how can the reviewer test the feature?

Local testing

## Checklist

Please ensure the following before requesting a review:

- [X] I have added a **changeset** for this PR
    - Every non-breaking change should be marked as a **patch**
    - To add a changeset, run `yarn changeset` and follow the prompts
- [ ] The changes are covered by relevant **tests**
- [X] I have verified the code works as intended locally
- [X] I have linked the related issue(s) if applicable

CLOSES #13397

### CODE REVIEW

File: packages/core/core-flows/src/order/workflows/update-tax-lines.ts [hunk 1]
```diff
@@ -197,7 +197,7 @@ export const updateOrderTaxLinesWorkflow = createWorkflow(
       options: { isList: false },
     }).config({ name: "order-query" })
 
-    const items = when({ input }, ({ input }) => {
+    const items = when("get-order-line-items", { input }, ({ input }) => {
```
Comment (willbouch) [inline packages/core/core-flows/src/order/workflows/update-tax-lines.ts:200]: Fixes a comment from Juan in Slack

**Review by olivermrbl — APPROVED** [review]
