### PR TITLE
fix(medusa): resolve user_id from user linked to secret key on draft order edit with api-key auth

### LINKED ISSUE #13859: [Bug]: Draft order edits using Secret api key
### Package.json file

```JSON
"dependencies": {
    "@medusajs/admin-sdk": "2.11.0",
    "@medusajs/cli": "2.11.0",
    "@medusajs/framework": "2.11.0",
    "@medusajs/medusa": "2.11.0",
    "@mikro-orm/core": "6.4.16",
    "@mikro-orm/knex": "6.4.16",
    "@mikro-orm/migrations": "6.4.16",
    "@mikro-orm/postgresql": "6.4.16",
    "awilix": "^8.0.1",
    "pg": "^8.16.3"
  },
```

### Node.js version

v22.17.0

### Database and its version

postgres:15

### Operating system name and version

Macos

### Browser name

*No response*

### What happended?

When editing a draft order via the endpoint /admin/draft-orders/{{draft-order-id}} using a secret API key, the system incorrectly assigns the API key ID (apk\_\*\*\*\*) as the user id of the edit.

### Expected behavior

The edit should be associated with a valid admin user, allowing the draft order to be viewed normally in the admin interface.

### Actual behavior

When opening the draft order, you get a 404 error and the following message:<br>FetchError: User with id: apk\_\*\*\*\* was not found

### Link to reproduction repo

[https://github.com/medusajs/medusa](<https://github.com/medusajs/medusa>)

### PR DESCRIPTION
**Pull request by NicolasGorga**
## Summary

**What** — What changes are introduced in this PR?

Resolve the `user_id` from the user linked to secret api key when updating a draft order with api-key auth type and set ti to `created_by` field of order change.

**Why** — Why are these changes relevant or necessary?  

Currently for this scenario, we incorrectly set the secret api key id as the `created_by` field of the corresponding `order_change` which causes authentication issues when that same user tries to interact with the change.

**How** — How have these changes been implemented?

Check the auth type in the draft order edit endpoint and if we identify it is `api-key` then instead of resolving the `user_id` from `req.auth_context.actor_id` that would point to the api key id, we search for the user that created the api key and set its id.

**Testing** — How have these changes been tested, or how can the reviewer test the feature?

Added tests.

---

## Examples

Provide examples or code snippets that demonstrate how this feature works, or how it can be used in practice.  
This helps with documentation and ensures maintainers can quickly understand and verify the change.

```ts
// Example usage
```

---

## Checklist

Please ensure the following before requesting a review:

- [x] I have added a **changeset** for this PR
    - Every non-breaking change should be marked as a **patch**
    - To add a changeset, run `yarn changeset` and follow the prompts
- [x] The changes are covered by relevant **tests**
- [x] I have verified the code works as intended locally
- [x] I have linked the related issue(s) if applicable

---

## Additional Context

Add any additional context, related issues, or references that might help the reviewer understand this PR.

fixes #13859 
closes SUP-2560

---

> [!NOTE]
> Ensure draft order edits authenticated via secret API keys attribute changes to the linked user, not the API key.
> 
> - **Admin Draft Orders API**:
>   - Update `POST /admin/draft-orders/:id` to resolve `user_id` from `api_key.created_by` when `actor_type` is `api-key`.
> - **Framework Middleware**:
>   - Add `set-secret-api-key-context` middleware to load `secret_key_context.created_by` from `api_key` and export it in `middlewares/index`.
>   - Register middleware for all `/admin*` routes in `packages/medusa/src/api/middlewares.ts`.
> - **Types**:
>   - Introduce `SecretKeyContext` and optional `secret_key_context` on `AuthenticatedMedusaRequest`.
> - **Tests**:
>   - Extend draft order integration tests to create a secret API key and assert order change `created_by` equals the linked user.
> - **Changeset**:
>   - Add patch changeset for `@medusajs/medusa`.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit 711ea00af09b1d1f82816b39c8ca17add9cc3554. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

File: packages/medusa/src/api/admin/draft-orders/[id]/route.ts [hunk 1]
```diff
@@ -39,10 +40,23 @@ export const POST = async (
...
+
+  const shouldResolveUser = authType === 'api-key'
+  if (shouldResolveUser) {
+    const {data: [apiKey]} = await query.graph({
+        entity: 'api_key',
+        fields: ['created_by'],
+        filters: { id: userId },
+    })
+    userId = apiKey.created_by
+  }
```
Comment (olivermrbl) [inline packages/medusa/src/api/admin/draft-orders/[id]/route.ts]: thought: This seems like something that should live in a middleware, as this is not really specific to draft orders ... think we should consider doing that instead

Also, this code does not follow our linting conventions

Comment (NicolasGorga) [reply packages/medusa/src/api/admin/draft-orders/[id]/route.ts]: Agreed I think we could follow something similar to existent `publishable_key_context` for `secret_key_context` and add the `created_by` prop in the new middleware, I started with this approach. Oh yes, forgot to run the formatter, will do :)

Comment (adrien2p) [reply packages/medusa/src/api/admin/draft-orders/[id]/route.ts]: I think there is an issue with your linter configuration ;)

File: integration-tests/http/__tests__/draft-order/admin/draft-order.spec.ts [hunk 2]
```diff
@@ -14,12 +14,14 @@ medusaIntegrationTestRunner({
...
     let shippingOptionHeavy: HttpTypes.AdminShippingOption
+    let apiKey: HttpTypes.AdminApiKeyResponse['api_key']
+    let userId: string
 
     beforeEach(async () => {
       const container = getContainer()
 
       await setupTaxStructure(container.resolve(ModuleRegistrationName.TAX))
-      await createAdminUser(dbConnection, adminHeaders, container)
+      userId = (await createAdminUser(dbConnection, adminHeaders, container)).user.id
```
Comment (adrien2p) [inline integration-tests/http/__tests__/draft-order/admin/draft-order.spec.ts]:
```suggestion
      userId = await createAdminUser(dbConnection, adminHeaders, container).then(user => user.id)
```

File: integration-tests/http/__tests__/draft-order/admin/draft-order.spec.ts [hunk 3]
```diff
@@ -217,6 +219,36 @@ medusaIntegrationTestRunner({
         expect(response.status).toBe(200)
         expect(response.data.draft_order.email).toBe("test_new@test.com")
       })
+
+      it("should set created_by to id of user linked to secret key", async () => {
```
Comment (adrien2p) [inline integration-tests/http/__tests__/draft-order/admin/draft-order.spec.ts]:
```suggestion
      it("should use the secret key linked user to set created_by", async () => {
```

File: packages/medusa/src/api/admin/draft-orders/[id]/route.ts (hunk 1 above)
Comment (adrien2p) [reply packages/medusa/src/api/admin/draft-orders/[id]/route.ts]: +1 for middleware

Comment (NicolasGorga) [reply packages/medusa/src/api/admin/draft-orders/[id]/route.ts]: Pushed commit with middleware, applied it to all `/admin` routes, could you let me know:

- if the middleware looks good to you
- if the way i applied to all admin routes is the correct way

File: packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts [hunk 4]
```diff
@@ -0,0 +1,52 @@
...
+  if (!req.auth_context) {
+    throw new MedusaError(
+      MedusaErrorTypes.INVALID_DATA,
+      "No `auth_context` found in request, make sure to apply this middleware after the `authenticate` middleware."
+    )
+  }
+
+  const shouldSkip = req.auth_context.actor_type !== "api-key"
+  if (shouldSkip) {
+    next()
```
Comment (adrien2p) [inline packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts]: todo: missing return here

File: packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+  const {
+    data: [apiKey],
+  } = await query.graph(
+    {
+      entity: "api_key",
+      fields: ["created_by"],
+      filters: {
+        id: req.auth_context.actor_id,
+      },
+      withDeleted: true,
```
Comment (adrien2p) [inline packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts:32]: Q: do we want the deleted one as well?

File: packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts [hunk 6]
```diff
@@ -0,0 +1,52 @@
...
+    },
+    {
+      cache: {
+        enable: true,
+      },
+    }
+  )
+
+  req.secret_key_context = {
```
Comment (adrien2p) [inline packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts:48]: Q: should we handle the case where nothing is found? is that possible

File: packages/medusa/src/api/admin/draft-orders/[id]/route.ts [hunk 7]
```diff
@@ -39,10 +40,23 @@ export const POST = async (
 ) => {
   const query = req.scope.resolve(ContainerRegistrationKeys.QUERY)
 
+  let userId = req.auth_context.actor_id
+  const authType = req.auth_context.actor_type as AuthType
+
+  const shouldResolveUser = authType === 'api-key'
+  if (shouldResolveUser) {
+    const {data: [apiKey]} = await query.graph({
```
Comment (adrien2p) [inline packages/medusa/src/api/admin/draft-orders/[id]/route.ts]: suggestion: your linter might need asjutment, I ve got mine on save

File: packages/medusa/src/api/middlewares.ts [hunk 8]
```diff
@@ -65,9 +65,16 @@ import { storeReturnReasonRoutesMiddlewares } from "./store/return-reasons/middl
 import { storeShippingOptionRoutesMiddlewares } from "./store/shipping-options/middlewares"
 import { adminShippingOptionTypeRoutesMiddlewares } from "./admin/shipping-option-types/middlewares"
 import { adminIndexRoutesMiddlewares } from "./admin/index/middlewares"
+import { setSecretApiKeyContext } from "@medusajs/framework"
 
 export default defineMiddlewares([
   ...storeRoutesMiddlewares,
+  {
+    matcher: "/admin*",
```
Comment (adrien2p) [inline packages/medusa/src/api/middlewares.ts:77]: suggestion: we might baked that in the framework route loader? cc @olivermrbl

Comment (NicolasGorga) [reply packages/medusa/src/api/middlewares.ts:77]: if you could then show me what would that approach look like it would be super :)

Comment (adrien2p) [reply packages/medusa/src/api/middlewares.ts:77]: I think it could somewhat follow this approach: https://github.com/medusajs/medusa/blob/7e3eb6e41316d7b04d32bc7186ed0c78de1aa539/packages/core/framework/src/http/router.ts#L240 let me know what you think. But we might also wait for oli's approval on that as he might have another idea for this

File: packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts (hunk 5 above)
Comment (NicolasGorga) [reply packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts:32]: I think so, since an action can be performed by an auth key that is active at the time, but then deleted. If we don't query including deleted, we wouldn't be able to resolve this information for audit/historic purposes.

File: packages/medusa/src/api/middlewares.ts (hunk 8 above)
Comment (NicolasGorga) [reply packages/medusa/src/api/middlewares.ts:77]: I like more the approach i did, since it is clearer as to where in the directory the middlewares are applied and are also applied in the same manner. Or is there a reason for this particular middleware to be applied differently?

File: packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts (hunk 6 above)
Comment (NicolasGorga) [reply packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts:48]: I made it so the middleware throws if it can't find `auth_context` in req, expecting the `authenticate` middleware to be applied before, so it would be guaranteed to exist when this line gets reached no?

File: packages/medusa/src/api/admin/draft-orders/[id]/route.ts (hunk 7 above)
Comment (NicolasGorga) [reply packages/medusa/src/api/admin/draft-orders/[id]/route.ts]: I've configured mine as well like that, though it is not working on save. I will troubleshoot it further and otherwise ask for your setup :)

File: packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts (hunk 4 above)
Comment (NicolasGorga) [reply packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts]: oops, done

File: packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts (hunk 6 above)
Comment (adrien2p) [reply packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts:48]: there is indeed the check on auth_context, but is it possible that the graph query returns nothing?

File: packages/medusa/src/api/middlewares.ts (hunk 8 above)
Comment (adrien2p) [reply packages/medusa/src/api/middlewares.ts:77]: it was more of a suggestion than anything else, but I dont have a strong opinion on that so I trust you 👍

Comment (NicolasGorga) [reply packages/medusa/src/api/middlewares.ts:77]: I'll resolve it then and just wait for Oli's input then :)

File: packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts (hunk 6 above)
Comment (NicolasGorga) [reply packages/core/framework/src/http/middlewares/set-secret-api-key-context.ts:48]: True that, added!

**Review by carlos-r-l-rodrigues — APPROVED** [review]

**Review by adrien2p — APPROVED** [review]
