### PR TITLE
fix(medusa, types): fix promotion HTTP types in cart

### LINKED ISSUE #11299: Issues with "promotions"
### What Medusa version and documentation are you using?

v2

### Preliminary Checks

- [x] This issue is not a duplicate. Before opening a new issue, please search existing issues: https://github.com/medusajs/medusa/issues

### Issue Summary

1. Cart Object schema at https://docs.medusajs.com/api/store#carts_cart_schema doesn't show "promotions" field.
2. Remove promotions at https://docs.medusajs.com/api/store#carts_deletecartsidpromotions doesn't show that I need to include promo_codes in the request body.
3. Also, "@medusajs/types": "^2.4.0" doesn't show that a cart can have a promotions field and there isn't a `StoreAddPromotion` type.

### How can this issue be resolved?

1. Fix the documentation for promotions
2. Add the promotion types in @medusajs/types. Would be also nice to have a `StoreAddPromotion` type for the request body.

### Are you interested in working on this issue?

- [ ] I would like to fix this issue

### PR DESCRIPTION
**Pull request by shahednasser**
- Add missing `promotions` property to `StoreCart`
- Add HTTP type payloads for add / remove promotion from cart routes

Closes #11299
Closes SUP-790

### CODE REVIEW

File: packages/core/types/src/http/cart/store/entities.ts [hunk 1]
```diff
@@ -80,3 +85,37 @@ export interface StoreCartShippingMethod extends BaseCartShippingMethod {
...
+   */
+  id: string
+  /**
+   * The promotion's code.
+   */
+  code?: string
+  /**
+   * Whether the promotion is applied automatically (without the customer needing to enter a code).
+   */
+  is_automatic?: boolean
```
Comment (olivermrbl) [inline packages/core/types/src/http/cart/store/entities.ts:100]: question: Don't think these can be undefined

**Review by olivermrbl — APPROVED** [review]
LGTM

File: packages/core/types/src/http/cart/store/entities.ts (hunk 1 above)
Comment (shahednasser) [reply packages/core/types/src/http/cart/store/entities.ts:100]: They're defined the same way in `StorePromotion`. Should I fix it in both places?
