### PR TITLE
fix(dashboard): PL creation - customers table customers count

### LINKED ISSUE #9210: Price Lists > Create > Customer availability: Table missing customers count
There is some issue while creating a price list for particular customer_groups.

I created the customer_group with customer. Now creating the price_list for that particular customer_group, so when I'm toggling to Customer availability” field and selecting the customer_group its giving me 0 customer under that customer_group, which is getting effected in my storefront, enabling that price list for all the customers.

PFA below
Screenshot 2024-09-20 at 5 04 23 PM

FYI: @olivermrbl

### PR DESCRIPTION
**Pull request by fPolic**
**What**
- display the number of customers in a group in the price list create flow

---

CLOSES https://github.com/medusajs/medusa/issues/9210
FIXES CC-517

### CODE REVIEW

File: packages/admin/dashboard/src/routes/price-lists/common/components/price-list-customer-group-rule-form/price-list-customer-group-rule-form.tsx [hunk 1]
```diff
@@ -59,9 +59,12 @@ export const PriceListCustomerGroupRuleForm = ({
     prefix: PREFIX,
   })
   const { customer_groups, count, isLoading, isError, error } =
-    useCustomerGroups(searchParams, {
-      placeholderData: keepPreviousData,
-    })
+    useCustomerGroups(
+      { ...searchParams, fields: "*customers.id" },
```
Comment (olivermrbl) [inline packages/admin/dashboard/src/routes/price-lists/common/components/price-list-customer-group-rule-form/price-list-customer-group-rule-form.tsx]: question: Do we need the `*` here? Would have expected this to just be `customers.id`

Comment (fPolic) [reply packages/admin/dashboard/src/routes/price-lists/common/components/price-list-customer-group-rule-form/price-list-customer-group-rule-form.tsx]: yes, fixed!

**Review by olivermrbl — APPROVED** [review]
