### PR TITLE
fix(medusa): pass calculated prices when fetching cart shipping options

### LINKED ISSUE #1877: Calculated shipping options: Can't see price until shipping method is added to the cart
## Bug report

Calculated shipping options: Can't see price for calculated shipping options until shipping method is added to the cart.

### Describe the bug

When I'm listing shipping options for a cart, some of the options use calculated prices, but the prices aren't calculated until I add them to the cart as a shipping method.

This is not an ideal experience, because customers won't be able to see estimates on the price, unless they cycle through all the options, adding each one to the cart as a shipping method, to see shipping price with the items in their cart.

It would be ideal if the API described here: https://docs.medusajs.com/api/store/shipping-option/retrieve-shipping-options-for-cart
used the fulfullment-provder's `calculatePrice` function with the cart: https://docs.medusajs.com/references/services/classes/FulfillmentProviderService#calculateprice

### System information

Medusa version (including plugins): 1.3.4
Node.js version: 14
Database: pg
Operating system: osx
Browser (if relevant): N/A

### PR DESCRIPTION
**Pull request by srindom**
Fixes #1877.

### CODE REVIEW

File: integration-tests/api/src/services/test-ful.js [hunk 1]
```diff
@@ -27,7 +27,8 @@ class TestFulService extends FulfillmentService {
     return false
```
Comment (dwene) [inline integration-tests/api/src/services/test-ful.js:27]: doesnt this need to be true for `canCalculate` to run?

File: integration-tests/api/src/services/test-ful.js [hunk 2]
```diff
@@ -27,7 +27,8 @@ class TestFulService extends FulfillmentService {
...
   }
 
-  calculatePrice() {
+  calculatePrice(data) {
+    return data.price
     throw Error("Manual Fulfillment service cannot calculatePrice")
```
Comment (dwene) [inline integration-tests/api/src/services/test-ful.js:32]: if we're returning above, seems like we don't need to throw here right? :)

**Review by olivermrbl — APPROVED** [review]
LGTM, feel free to merge after having addressed @dwene's comments 💪
