### PR TITLE
fix(medusa): Double tax issue on return refund amount

### LINKED ISSUE #4686: Incorrect amount deducted for return shipping
Describe the bug
When receiving returns an incorrect amount is deducted from the refund for most Danish orders (but not all)

System information
"@medusajs/admin": "6.0.1",
"@medusajs/cache-redis": "1.8.8",
"@medusajs/event-bus-redis": "1.8.8",
"@medusajs/inventory": "1.9.1",
"@medusajs/medusa": "^1.12.1",
"@medusajs/medusa-cli": "1.3.16",
"@medusajs/stock-location": "1.9.1",
"@types/express": "^4.17.17",
"babel-preset-medusa-package": "1.1.19",
"contentful": "^7.14.7",
"cors": "^2.8.5",
"cross-env": "^7.0.2",
"csv-stringify": "5.3.2",
"easy-soap-request": "^3.3.3",
"express": "^4.17.1",
"joi": "^17.3.0",
"medusa-core-utils": "1.2.0",
"medusa-file-spaces": "1.3.7",
"medusa-fulfillment-webshipper": "1.3.11-snapshot-20230626084333",
"medusa-interfaces": "1.3.7",
"medusa-payment-adyen": "1.1.44",
"medusa-payment-klarna": "1.3.10",
"medusa-payment-manual": "1.0.24",
"medusa-payment-paypal": "6.0.1",
"medusa-payment-stripe": "6.0.1",
"medusa-plugin-brightpearl": "1.3.10-snapshot-20230621150344",
"medusa-plugin-contentful": "1.2.10",
"medusa-plugin-discount-generator": "1.1.27",
"medusa-plugin-ip-lookup": "1.2.8",
"medusa-plugin-meilisearch": "2.0.8",
"medusa-plugin-restock-notification": "7.0.2",
"medusa-plugin-segment": "1.3.6",
"medusa-plugin-sendgrid": "1.3.9",
"medusa-plugin-sentry": "^1.4.2",
"medusa-plugin-slack-notification": "1.3.9",
"medusa-plugin-wishlist": "1.1.43",
"medusa-test-utils": "^1.1.41",

Steps to reproduce the behavior
receive returns

Screenshot 2023-08-03 at 11 04 40

Expected behavior
the amount is correct

### PR DESCRIPTION
**Pull request by josipmatichr**
Closes #4686

### CODE REVIEW

**Comment by olivermrbl** [comment]
@josipmatichr do you want me to publish a snapshot for you to test these changes?

**Comment by josipmatichr** [comment]
@olivermrbl that would be amazing, thank you! 🙌

**Comment by olivermrbl** [comment]
```
@medusajs/medusa@1.15.1-canary-20230830170958
```

File: integration-tests/api/__tests__/returns/index.js [hunk 1]
```diff
@@ -189,6 +189,56 @@ describe("/admin/orders", () => {
     )
   })
 
+  test("creates a store return w. new tax system + shipping", async () => {
+    await adminSeeder(dbConnection)
+    const order = await createReturnableOrder(dbConnection, { oldTaxes: false })
+    const returnOption = await simpleShippingOptionFactory(dbConnection, {
```
Comment (srindom) [inline integration-tests/api/__tests__/returns/index.js:195]: question: shouldn't this be set up with a tax-inclusive price since that is the scenario we are having issues with?

Comment (josipmatichr) [reply integration-tests/api/__tests__/returns/index.js:195]: @srindom that is true - however the functionality is relying on `TaxInclusivePricingFeatureFlag` to determine wether the price is tax inclusive and this feature flag is not enabled in integration-tests config and setting it might potentially collide with other test results. What do you think should be the best approach here?

Comment (srindom) [reply integration-tests/api/__tests__/returns/index.js:195]: You can place the test in this file `integration-tests/api/__tests__/returns/ff-tax-inclusive-pricing.js` instead - it will have the feature flag enabled :)

Comment (josipmatichr) [reply integration-tests/api/__tests__/returns/index.js:195]: ahh, totally missed that - added, should be covered now!
