### PR TITLE
fix(dashboard): tax region override too large payload

### LINKED ISSUE #13644: [Bug]: "PayloadTooLargeError" when saving tax rate overrides with large product catalogs
### Package.json file

```JSON
{
  "name": "medusa",
  "version": "0.0.1",
  "description": "A starter for Medusa projects.",
  "author": "Medusa (https://medusajs.com)",
  "license": "MIT",
  "keywords": [
    "sqlite",
    "postgres",
    "typescript",
    "ecommerce",
    "headless",
    "medusa"
  ],
  "scripts": {
    "build": "medusa build",
    "db:create": "medusa db:create",
    "db:seed": "medusa exec ./src/scripts/seed.ts",
    "db:migrate": "medusa db:migrate",
    "db:rollback": "medusa db:rollback",
    "predeploy": "medusa db:migrate",
    "start": "medusa start",
    "dev": "medusa develop",
    "test:integration:http": "TEST_TYPE=integration:http NODE_OPTIONS=--experimental-vm-modules jest --silent=false --runInBand --forceExit",
    "test:integration:modules": "TEST_TYPE=integration:modules NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit",
    "test:unit": "TEST_TYPE=unit NODE_OPTIONS=--experimental-vm-modules jest --silent --runInBand --forceExit"
  },
  "dependencies": {
    "@hookform/resolvers": "^3.3.0",
    "@medusajs/admin-sdk": "^2.8.7",
    "@medusajs/cli": "^2.8.7",
    "@medusajs/dashboard": "^2.8.7",
    "@medusajs/framework": "^2.8.7",
    "@medusajs/icons": "^2.8.7",
    "@medusajs/loyalty-plugin": "0.0.7-preview.3",
    "@medusajs/medusa": "^2.8.7",
    "@mikro-orm/core": "6.4.3",
    "@mikro-orm/knex": "6.4.3",
    "@mikro-orm/migrations": "6.4.3",
    "@mikro-orm/postgresql": "6.4.3",
    "@opentelemetry/api": "^1.9.0",
    "@opentelemetry/exporter-trace-otlp-grpc": "^0.202.0",
    "@opentelemetry/instrumentation-pg": "^0.54.0",
    "@opentelemetry/resources": "^2.0.1",
    "@opentelemetry/sdk-node": "^0.202.0",
    "@opentelemetry/sdk-trace-node": "^2.0.1",
    "@sanity/client": "^6.28.3",
    "@sentry/node": "^9.33.0",
    "@sentry/opentelemetry-node": "^7.114.0",
    "@tanstack/react-table": "^8.20.5",
    "@uiw/react-json-view": "2.0.0-alpha.30",
    "algoliasearch": "^5.20.4",
    "awilix": "^8.0.1",
    "customerio-node": "^4.1.1",
    "i18next": "^25.3.0",
    "jsonwebtoken": "^9.0.2",
    "moment": "^2.30.1",
    "pdfkit": "^0.17.1",
    "pg": "^8.13.0",
    "react-hook-form": "^7.55.0",
    "react-i18next": "^15.5.1",
    "react-router-dom": "6.20.1",
    "recharts": "^3.0.2",
    "zod": "3.22.4"
  },
  "devDependencies": {
    "@medusajs/js-sdk": "^2.8.7",
    "@medusajs/test-utils": "^2.8.7",
    "@medusajs/ui": "^4.0.17",
    "@mikro-orm/cli": "6.4.3",
    "@swc/core": "1.5.7",
    "@swc/jest": "^0.2.36",
    "@tanstack/react-query": "5.64.2",
    "@types/jest": "^29.5.13",
    "@types/node": "^20.0.0",
    "@types/react": "^18.3.2",
    "@types/react-dom": "^18.2.25",
    "jest": "^29.7.0",
    "prop-types": "^15.8.1",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "ts-node": "^10.9.2",
    "typescript": "^5.6.2",
    "vite": "^5.2.11"
  },
  "engines": {
    "node": ">=20"
  }
}
```

### Node.js version

v23.10.0

### Database and its version

16.2

### Operating system name and version

MacOS

### Browser name

Chrome

### Related to 
#12921 

After the fix for the URL parameter size issue, a new related problem occurs: when attempting to save tax rate overrides or load the overrides dropdown, a "PayloadTooLargeError" is thrown due to the request body exceeding server payload size limits.

### To Reproduce

Set up a Medusa store with ~3000 products
Configure tax rate overrides affecting ~1000+ products
Navigate to the tax override edit page
Attempt to save changes to the tax rate override
Observe the "PayloadTooLargeError"

### Alternative reproduction:

Try to load the overrides dropdown selector → Same error occurs

### Expected behavior

Tax rate overrides should save successfully regardless of the number of products affected, with proper handling of large datasets.

### Actual behavior

Image
Image

### Error details:

```
PayloadTooLargeError: request entity too large
POST /admin/tax-rates/txr_XXX
```

### Link to reproduction repo

/

### PR DESCRIPTION
**Pull request by NicolasGorga**
## Summary

**What** — What changes are introduced in this PR?

Fix to limit the amount of ids passed to render the TaxRegion override card tooltip showing the different elements the override is for.

**Why** — Why are these changes relevant or necessary?  

If you have a large amount of elements linked to the tax region override, when you uncollapse the tax override detail, the query issued to construct the tooltip passes all the ids via query params and you end up with a PayloadTooLarge error.

**How** — How have these changes been implemented?

Updated the `useReferenceValues` hook to limit the ids requested to 10, for the different linked element types (products, product types and shipping options), similar to what is done in the tax override edit form.

I've also corrected the `additional` property computation, which is used to show the 'and [additional] more values', since we now limit the display elements.

**Testing** — How have these changes been tested, or how can the reviewer test the feature?

Tested it in a local project and verified that we don't get the PayloadTooLarge error anymore and the tooltip shows the expected values.

---

## Examples

Provide examples or code snippets that demonstrate how this feature works, or how it can be used in practice.  
This helps with documentation and ensures maintainers can quickly understand and verify the change.

```ts
// Example usage
```

---

## Checklist

Please ensure the following before requesting a review:

- [x] I have added a **changeset** for this PR
    - Every non-breaking change should be marked as a **patch**
    - To add a changeset, run `yarn changeset` and follow the prompts
- [] The changes are covered by relevant **tests**
- [x] I have verified the code works as intended locally
- [x] I have linked the related issue(s) if applicable

---

## Additional Context

Add any additional context, related issues, or references that might help the reviewer understand this PR.

Fixes #13644

### CODE REVIEW

File: packages/admin/dashboard/src/routes/tax-regions/common/components/tax-override-card/tax-override-card.tsx [hunk 1]
```diff
@@ -343,10 +344,9 @@ const useReferenceValues = (
       return {
         labels: products.products?.map((product) => product.title),
         isPending: products.isPending,
-        additional:
-          products.products && products.count
-            ? products.count - products.products.length
-            : 0,
+        additional: ids.length > DISPLAY_OVERRIDE_ITEMS_LIMIT
+			? ids.length - DISPLAY_OVERRIDE_ITEMS_LIMIT
+			: 0,
```
Comment (adrien2p) [inline packages/admin/dashboard/src/routes/tax-regions/common/components/tax-override-card/tax-override-card.tsx]: suggestion: should we extract that above the switch? (e.g line 341)

**Review by adrien2p — APPROVED** [review]

**Review by willbouch — APPROVED** [review]
Just Adrien's comment and we are good to go

File: packages/admin/dashboard/src/routes/tax-regions/common/components/tax-override-card/tax-override-card.tsx (hunk 1 above)
Comment (NicolasGorga) [reply packages/admin/dashboard/src/routes/tax-regions/common/components/tax-override-card/tax-override-card.tsx]: Agree, updated!

**Review by willbouch — APPROVED** [review]
